// File generated by Gambit v4.9.3
// Link info: (409003 (js ()) "exo01" (("exo01")) (module_register glo peps make_interned_symbol string sp stack r0 r1 ffi poll pollcount wrong_nargs nargs) () (button-click-set! main body-append document.write exo01#) () #f)

var g_cst0_G_exo01 = new G_ScmString([60,104,49,62,72,101,108,108,111,32,33,32,84,104,105,115,32,105,115,32,109,121,32,110,101,119,32,104,49,60,47,104,49,62]);

var g_cst1_G_exo01 = new G_ScmString([60,105,110,112,117,116,32,116,121,112,101,61,34,115,117,98,109,105,116,34,32,118,97,108,117,101,61,34,65,100,100,32,72,101,108,108,111,32,33,34,32,111,110,99,108,105,99,107,61,34,100,105,115,112,108,97,121,72,101,108,108,111,40,41,34,62,60,47,105,110,112,117,116,62]);

var g_cst2_G_exo01 = new G_ScmString([60,104,49,62,72,101,108,108,111,32,87,111,114,108,100,32,33,60,47,104,49,62]);

function g_bb1_exo01_23_() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_exo01_23_);
  }
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_exo01_23_);
  } else {
    g_nargs = 0;
    return g_bb1_main();
  }
}

g_bb1_exo01_23_.id = 0;
g_bb1_exo01_23_.parent = g_bb1_exo01_23_;
g_bb1_exo01_23_.nfree = -1;
g_bb1_exo01_23_._name = g_make_interned_symbol("exo01#");
g_bb1_exo01_23_.ctrlpts = null;
g_bb1_exo01_23_.info = false;

function g_bb2_exo01_23_() {
  g_nargs = 0;
  return g_bb1_main();
}

g_bb2_exo01_23_.id = 1;
g_bb2_exo01_23_.parent = g_bb1_exo01_23_;


g_bb1_exo01_23_.ctrlpts = [g_bb1_exo01_23_,g_bb2_exo01_23_];


g_peps["exo01#"] = g_bb1_exo01_23_;
g_glo["exo01#"] = g_bb1_exo01_23_;

function g_bb1_document_2e_write() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_document_2e_write);
  }
  document.write(g_scm2host(g_r1));g_r1 = void 0;
  return g_r0;
}

g_bb1_document_2e_write.id = 0;
g_bb1_document_2e_write.parent = g_bb1_document_2e_write;
g_bb1_document_2e_write.nfree = -1;
g_bb1_document_2e_write._name = g_make_interned_symbol("document.write");
g_bb1_document_2e_write.ctrlpts = null;
g_bb1_document_2e_write.info = false;


g_bb1_document_2e_write.ctrlpts = [g_bb1_document_2e_write];


g_peps["document.write"] = g_bb1_document_2e_write;
g_glo["document.write"] = g_bb1_document_2e_write;

function g_bb1_body_2d_append() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_body_2d_append);
  }
  document.getElementById("body").innerHTML += g_scm2host(g_r1);g_r1 = void 0;
  return g_r0;
}

g_bb1_body_2d_append.id = 0;
g_bb1_body_2d_append.parent = g_bb1_body_2d_append;
g_bb1_body_2d_append.nfree = -1;
g_bb1_body_2d_append._name = g_make_interned_symbol("body-append");
g_bb1_body_2d_append.ctrlpts = null;
g_bb1_body_2d_append.info = false;


g_bb1_body_2d_append.ctrlpts = [g_bb1_body_2d_append];


g_peps["body-append"] = g_bb1_body_2d_append;
g_glo["body-append"] = g_bb1_body_2d_append;

function g_bb1_button_2d_click_2d_set_21_() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_button_2d_click_2d_set_21_);
  }
  displayHello = g_scm2host(g_r1);g_r1 = void 0;
  return g_r0;
}

g_bb1_button_2d_click_2d_set_21_.id = 0;
g_bb1_button_2d_click_2d_set_21_.parent = g_bb1_button_2d_click_2d_set_21_;
g_bb1_button_2d_click_2d_set_21_.nfree = -1;
g_bb1_button_2d_click_2d_set_21_._name = g_make_interned_symbol("button-click-set!");
g_bb1_button_2d_click_2d_set_21_.ctrlpts = null;
g_bb1_button_2d_click_2d_set_21_.info = false;


g_bb1_button_2d_click_2d_set_21_.ctrlpts = [g_bb1_button_2d_click_2d_set_21_];


g_peps["button-click-set!"] = g_bb1_button_2d_click_2d_set_21_;
g_glo["button-click-set!"] = g_bb1_button_2d_click_2d_set_21_;

function g_bb1_main() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_main);
  }
  g_stack[g_sp+1] = g_r0;
  g_r1 = g_bb6_main;
  ++g_sp;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_main);
  } else {
    g_r0 = g_bb3_main;
    g_nargs = 1;
    return g_bb1_button_2d_click_2d_set_21_();
  }
}

g_bb1_main.id = 0;
g_bb1_main.parent = g_bb1_main;
g_bb1_main.nfree = -1;
g_bb1_main._name = g_make_interned_symbol("main");
g_bb1_main.ctrlpts = null;
g_bb1_main.info = false;

function g_bb6_main() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb6_main);
  }
  g_r1 = g_cst0_G_exo01;
  if (--g_pollcount === 0) {
    return g_poll(g_bb7_main);
  } else {
    g_nargs = 1;
    return g_bb1_body_2d_append();
  }
}

g_bb6_main.id = 1;
g_bb6_main.parent = g_bb1_main;
g_bb6_main.nfree = -1;

function g_bb2_main() {
  g_r0 = g_bb3_main;
  g_nargs = 1;
  return g_bb1_button_2d_click_2d_set_21_();
}

g_bb2_main.id = 2;
g_bb2_main.parent = g_bb1_main;

function g_bb3_main() { // return-point
  g_r1 = g_cst1_G_exo01;
  g_r0 = g_bb4_main;
  g_nargs = 1;
  return g_bb1_document_2e_write();
}

g_bb3_main.id = 3;
g_bb3_main.parent = g_bb1_main;
g_bb3_main.fs = 1;
g_bb3_main.link = 1;

function g_bb7_main() {
  g_nargs = 1;
  return g_bb1_body_2d_append();
}

g_bb7_main.id = 4;
g_bb7_main.parent = g_bb1_main;

function g_bb4_main() { // return-point
  g_r1 = g_cst2_G_exo01;
  g_r0 = g_stack[g_sp];
  if (--g_pollcount === 0) {
    return g_poll(g_bb5_main);
  } else {
    g_nargs = 1;
    --g_sp;
    return g_bb1_document_2e_write();
  }
}

g_bb4_main.id = 5;
g_bb4_main.parent = g_bb1_main;
g_bb4_main.fs = 1;
g_bb4_main.link = 1;

function g_bb5_main() {
  g_nargs = 1;
  --g_sp;
  return g_bb1_document_2e_write();
}

g_bb5_main.id = 6;
g_bb5_main.parent = g_bb1_main;


g_bb1_main.ctrlpts = [g_bb1_main,g_bb6_main,g_bb2_main,g_bb3_main,g_bb7_main,g_bb4_main,g_bb5_main];


g_peps["main"] = g_bb1_main;
g_glo["main"] = g_bb1_main;

g_module_register([[g_make_interned_symbol("exo01")],[],null,1,g_bb1_exo01_23_,false]);

