// File generated by Gambit v4.8.8
// Link info: (408008 (js ()) "app" (("app")) (module_register peps make_interned_symbol ffi glo check_procedure poll pollcount string r1 r0 sp stack wrong_nargs nargs) (mysquare) (body-append body-append-text-br DOM-getById | app| mysquare DOM-body body-prepend-br body-append-br DOM-log) (mysquare) #f)

var g_cst0_app = new G_ScmString([85,110,32,112,114,101,109,105,101,114,32,116,101,120,116,32,97,118,101,99,32,108,105,110,101,32,98,114,101,97,107]);

var g_cst1_app = new G_ScmString([101,116,32,117,110,32,115,101,99,111,110,100,32,115,97,110,115,32,108,105,110,101,32,98,114,101,97,107,46,32]);

var g_cst2_app = new G_ScmString([106,101,32,116,101,32,118,111,108,101,32,108,97,32,112,108,97,99,101,32,100,117,32,112,114,101,109,115]);

var g_cst3_app = new G_ScmString([99,101,99,105,32,101,115,116,32,100,117,32,60,98,62,116,101,120,116,32,111,110,108,121,60,47,98,62,44,32,108,101,115,32,116,97,103,115,32,110,101,32,109,97,114,99,104,101,110,116,32,112,97,115]);

var g_cst4_app = new G_ScmString([60,100,105,118,32,105,100,61,39,114,101,100,45,115,113,117,97,114,101,39,32,115,116,121,108,101,61,39,98,97,99,107,103,114,111,117,110,100,58,114,101,100,59,104,101,105,103,104,116,58,51,48,48,112,120,59,119,105,100,116,104,58,51,48,48,112,120,39,62,60,47,100,105,118,62]);

var g_cst5_app = new G_ScmString([114,101,100,45,115,113,117,97,114,101]);

var g_cst6_app = new G_ScmString([60,98,114,47,62]);

var g_cst7_app = new G_ScmString([60,98,114,47,62]);

var g_cst8_app = new G_ScmString([60,98,114,47,62]);

function g_bb1__20_app() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1__20_app);
  }
  g_stack[g_sp+1] = g_r0;
  g_r1 = g_cst0_app;
  g_r0 = g_bb3__20_app;
  ++g_sp;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2__20_app);
  } else {
    g_nargs = 1;
    if (--g_pollcount === 0) {
      return g_poll(g_check_procedure(g_bb1_body_2d_append_2d_br));
    } else {
      return g_check_procedure(g_bb1_body_2d_append_2d_br)();
    }
  }
}

g_bb1__20_app.id = 0;
g_bb1__20_app.parent = g_bb1__20_app;
g_bb1__20_app.nfree = -1;
g_bb1__20_app._name = g_make_interned_symbol(" app");
g_bb1__20_app.ctrlpts = null;
g_bb1__20_app.info = false;

function g_bb3__20_app() { // return-point
  g_r1 = g_cst1_app;
  g_r0 = g_bb4__20_app;
  g_nargs = 1;
  if (--g_pollcount === 0) {
    return g_poll(g_check_procedure(g_bb1_body_2d_append));
  } else {
    return g_check_procedure(g_bb1_body_2d_append)();
  }
}

g_bb3__20_app.id = 1;
g_bb3__20_app.parent = g_bb1__20_app;
g_bb3__20_app.fs = 1;
g_bb3__20_app.link = 1;

function g_bb2__20_app() {
  g_nargs = 1;
  if (--g_pollcount === 0) {
    return g_poll(g_check_procedure(g_bb1_body_2d_append_2d_br));
  } else {
    return g_check_procedure(g_bb1_body_2d_append_2d_br)();
  }
}
function g_bb4__20_app() { // return-point
  g_r1 = g_cst2_app;
  g_r0 = g_bb5__20_app;
  g_nargs = 1;
  if (--g_pollcount === 0) {
    return g_poll(g_check_procedure(g_bb1_body_2d_prepend_2d_br));
  } else {
    return g_check_procedure(g_bb1_body_2d_prepend_2d_br)();
  }
}

g_bb4__20_app.id = 2;
g_bb4__20_app.parent = g_bb1__20_app;
g_bb4__20_app.fs = 1;
g_bb4__20_app.link = 1;

function g_bb5__20_app() { // return-point
  g_r1 = g_cst3_app;
  g_r0 = g_bb6__20_app;
  g_nargs = 1;
  if (--g_pollcount === 0) {
    return g_poll(g_check_procedure(g_bb1_body_2d_append_2d_text_2d_br));
  } else {
    return g_check_procedure(g_bb1_body_2d_append_2d_text_2d_br)();
  }
}

g_bb5__20_app.id = 3;
g_bb5__20_app.parent = g_bb1__20_app;
g_bb5__20_app.fs = 1;
g_bb5__20_app.link = 1;

function g_bb6__20_app() { // return-point
  g_r1 = g_cst4_app;
  g_r0 = g_bb7__20_app;
  g_nargs = 1;
  if (--g_pollcount === 0) {
    return g_poll(g_check_procedure(g_bb1_body_2d_append));
  } else {
    return g_check_procedure(g_bb1_body_2d_append)();
  }
}

g_bb6__20_app.id = 4;
g_bb6__20_app.parent = g_bb1__20_app;
g_bb6__20_app.fs = 1;
g_bb6__20_app.link = 1;

function g_bb7__20_app() { // return-point
  g_r1 = g_cst5_app;
  g_r0 = g_bb8__20_app;
  g_nargs = 1;
  if (--g_pollcount === 0) {
    return g_poll(g_check_procedure(g_bb1_DOM_2d_getById));
  } else {
    return g_check_procedure(g_bb1_DOM_2d_getById)();
  }
}

g_bb7__20_app.id = 5;
g_bb7__20_app.parent = g_bb1__20_app;
g_bb7__20_app.fs = 1;
g_bb7__20_app.link = 1;

function g_bb8__20_app() { // return-point
  g_glo["mysquare"] = g_r1;
  g_r1 = g_glo["mysquare"];
  g_r0 = g_bb9__20_app;
  g_nargs = 1;
  if (--g_pollcount === 0) {
    return g_poll(g_check_procedure(g_bb1_DOM_2d_log));
  } else {
    return g_check_procedure(g_bb1_DOM_2d_log)();
  }
}

g_bb8__20_app.id = 6;
g_bb8__20_app.parent = g_bb1__20_app;
g_bb8__20_app.fs = 1;
g_bb8__20_app.link = 1;

function g_bb9__20_app() { // return-point
  g_r0 = g_bb10__20_app;
  g_nargs = 0;
  if (--g_pollcount === 0) {
    return g_poll(g_check_procedure(g_bb1_DOM_2d_body));
  } else {
    return g_check_procedure(g_bb1_DOM_2d_body)();
  }
}

g_bb9__20_app.id = 7;
g_bb9__20_app.parent = g_bb1__20_app;
g_bb9__20_app.fs = 1;
g_bb9__20_app.link = 1;

function g_bb10__20_app() { // return-point
  g_r0 = g_stack[g_sp];
  if (--g_pollcount === 0) {
    return g_poll(g_bb11__20_app);
  } else {
    g_nargs = 0;
    --g_sp;
    if (--g_pollcount === 0) {
      return g_poll(g_check_procedure(g_bb1_DOM_2d_body));
    } else {
      return g_check_procedure(g_bb1_DOM_2d_body)();
    }
  }
}

g_bb10__20_app.id = 8;
g_bb10__20_app.parent = g_bb1__20_app;
g_bb10__20_app.fs = 1;
g_bb10__20_app.link = 1;

function g_bb11__20_app() {
  g_nargs = 0;
  --g_sp;
  if (--g_pollcount === 0) {
    return g_poll(g_check_procedure(g_bb1_DOM_2d_body));
  } else {
    return g_check_procedure(g_bb1_DOM_2d_body)();
  }
}

g_bb1__20_app.ctrlpts = [g_bb1__20_app,g_bb3__20_app,g_bb4__20_app,g_bb5__20_app,g_bb6__20_app,g_bb7__20_app,g_bb8__20_app,g_bb9__20_app,g_bb10__20_app];


g_peps[" app"] = g_bb1__20_app;
g_glo[" app"] = g_bb1__20_app;

function g_bb1_DOM_2d_getById() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_DOM_2d_getById);
  }
  g_r1 = (document.getElementById(g_scm2host(g_r1)));
  if (--g_pollcount === 0) {
    return g_poll(g_r0);
  } else {
    return g_r0;
  }
}

g_bb1_DOM_2d_getById.id = 0;
g_bb1_DOM_2d_getById.parent = g_bb1_DOM_2d_getById;
g_bb1_DOM_2d_getById.nfree = -1;
g_bb1_DOM_2d_getById._name = g_make_interned_symbol("DOM-getById");
g_bb1_DOM_2d_getById.ctrlpts = null;
g_bb1_DOM_2d_getById.info = false;


g_bb1_DOM_2d_getById.ctrlpts = [g_bb1_DOM_2d_getById];


g_peps["DOM-getById"] = g_bb1_DOM_2d_getById;
g_glo["DOM-getById"] = g_bb1_DOM_2d_getById;

function g_bb1_DOM_2d_body() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_DOM_2d_body);
  }
  g_r1 = body;
  if (--g_pollcount === 0) {
    return g_poll(g_r0);
  } else {
    return g_r0;
  }
}

g_bb1_DOM_2d_body.id = 0;
g_bb1_DOM_2d_body.parent = g_bb1_DOM_2d_body;
g_bb1_DOM_2d_body.nfree = -1;
g_bb1_DOM_2d_body._name = g_make_interned_symbol("DOM-body");
g_bb1_DOM_2d_body.ctrlpts = null;
g_bb1_DOM_2d_body.info = false;


g_bb1_DOM_2d_body.ctrlpts = [g_bb1_DOM_2d_body];


g_peps["DOM-body"] = g_bb1_DOM_2d_body;
g_glo["DOM-body"] = g_bb1_DOM_2d_body;

function g_bb1_DOM_2d_log() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_DOM_2d_log);
  }
  console.log(g_r1);g_r1 = void 0;
  if (--g_pollcount === 0) {
    return g_poll(g_r0);
  } else {
    return g_r0;
  }
}

g_bb1_DOM_2d_log.id = 0;
g_bb1_DOM_2d_log.parent = g_bb1_DOM_2d_log;
g_bb1_DOM_2d_log.nfree = -1;
g_bb1_DOM_2d_log._name = g_make_interned_symbol("DOM-log");
g_bb1_DOM_2d_log.ctrlpts = null;
g_bb1_DOM_2d_log.info = false;


g_bb1_DOM_2d_log.ctrlpts = [g_bb1_DOM_2d_log];


g_peps["DOM-log"] = g_bb1_DOM_2d_log;
g_glo["DOM-log"] = g_bb1_DOM_2d_log;

function g_bb1_body_2d_prepend_2d_br() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_body_2d_prepend_2d_br);
  }
  body.innerHTML = g_scm2host(g_r1) + g_scm2host(g_cst6_app) + body.innerHTML;g_r1 = void 0;
  if (--g_pollcount === 0) {
    return g_poll(g_r0);
  } else {
    return g_r0;
  }
}

g_bb1_body_2d_prepend_2d_br.id = 0;
g_bb1_body_2d_prepend_2d_br.parent = g_bb1_body_2d_prepend_2d_br;
g_bb1_body_2d_prepend_2d_br.nfree = -1;
g_bb1_body_2d_prepend_2d_br._name = g_make_interned_symbol("body-prepend-br");
g_bb1_body_2d_prepend_2d_br.ctrlpts = null;
g_bb1_body_2d_prepend_2d_br.info = false;


g_bb1_body_2d_prepend_2d_br.ctrlpts = [g_bb1_body_2d_prepend_2d_br];


g_peps["body-prepend-br"] = g_bb1_body_2d_prepend_2d_br;
g_glo["body-prepend-br"] = g_bb1_body_2d_prepend_2d_br;

function g_bb1_body_2d_append() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_body_2d_append);
  }
  body.innerHTML += g_scm2host(g_r1);g_r1 = void 0;
  if (--g_pollcount === 0) {
    return g_poll(g_r0);
  } else {
    return g_r0;
  }
}

g_bb1_body_2d_append.id = 0;
g_bb1_body_2d_append.parent = g_bb1_body_2d_append;
g_bb1_body_2d_append.nfree = -1;
g_bb1_body_2d_append._name = g_make_interned_symbol("body-append");
g_bb1_body_2d_append.ctrlpts = null;
g_bb1_body_2d_append.info = false;


g_bb1_body_2d_append.ctrlpts = [g_bb1_body_2d_append];


g_peps["body-append"] = g_bb1_body_2d_append;
g_glo["body-append"] = g_bb1_body_2d_append;

function g_bb1_body_2d_append_2d_br() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_body_2d_append_2d_br);
  }
  body.innerHTML+= g_scm2host(g_r1) + g_scm2host(g_cst7_app);g_r1 = void 0;
  if (--g_pollcount === 0) {
    return g_poll(g_r0);
  } else {
    return g_r0;
  }
}

g_bb1_body_2d_append_2d_br.id = 0;
g_bb1_body_2d_append_2d_br.parent = g_bb1_body_2d_append_2d_br;
g_bb1_body_2d_append_2d_br.nfree = -1;
g_bb1_body_2d_append_2d_br._name = g_make_interned_symbol("body-append-br");
g_bb1_body_2d_append_2d_br.ctrlpts = null;
g_bb1_body_2d_append_2d_br.info = false;


g_bb1_body_2d_append_2d_br.ctrlpts = [g_bb1_body_2d_append_2d_br];


g_peps["body-append-br"] = g_bb1_body_2d_append_2d_br;
g_glo["body-append-br"] = g_bb1_body_2d_append_2d_br;

function g_bb1_body_2d_append_2d_text_2d_br() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_body_2d_append_2d_text_2d_br);
  }
  body.append(g_scm2host(g_r1));g_r1 = g_cst8_app;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_body_2d_append_2d_text_2d_br);
  } else {
    g_nargs = 1;
    if (--g_pollcount === 0) {
      return g_poll(g_check_procedure(g_bb1_body_2d_append));
    } else {
      return g_check_procedure(g_bb1_body_2d_append)();
    }
  }
}

g_bb1_body_2d_append_2d_text_2d_br.id = 0;
g_bb1_body_2d_append_2d_text_2d_br.parent = g_bb1_body_2d_append_2d_text_2d_br;
g_bb1_body_2d_append_2d_text_2d_br.nfree = -1;
g_bb1_body_2d_append_2d_text_2d_br._name = g_make_interned_symbol("body-append-text-br");
g_bb1_body_2d_append_2d_text_2d_br.ctrlpts = null;
g_bb1_body_2d_append_2d_text_2d_br.info = false;

function g_bb2_body_2d_append_2d_text_2d_br() {
  g_nargs = 1;
  if (--g_pollcount === 0) {
    return g_poll(g_check_procedure(g_bb1_body_2d_append));
  } else {
    return g_check_procedure(g_bb1_body_2d_append)();
  }
}

g_bb1_body_2d_append_2d_text_2d_br.ctrlpts = [g_bb1_body_2d_append_2d_text_2d_br];


g_peps["body-append-text-br"] = g_bb1_body_2d_append_2d_text_2d_br;
g_glo["body-append-text-br"] = g_bb1_body_2d_append_2d_text_2d_br;

g_module_register([g_make_interned_symbol("app"),g_bb1__20_app,1,null,false]);

