// File generated by Gambit v4.9.3
// Link info: (409003 (js ()) "exo00" (("exo00")) (module_register glo peps make_interned_symbol string r0 r1 ffi poll pollcount wrong_nargs nargs) () (document.write main exo00#) () #f)

var g_cst0_G_exo00 = new G_ScmString([60,104,49,62,72,101,108,108,111,32,87,111,114,108,100,32,33,60,47,104,49,62]);

function g_bb1_exo00_23_() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_exo00_23_);
  }
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_exo00_23_);
  } else {
    g_nargs = 0;
    return g_bb1_main();
  }
}

g_bb1_exo00_23_.id = 0;
g_bb1_exo00_23_.parent = g_bb1_exo00_23_;
g_bb1_exo00_23_.nfree = -1;
g_bb1_exo00_23_._name = g_make_interned_symbol("exo00#");
g_bb1_exo00_23_.ctrlpts = null;
g_bb1_exo00_23_.info = false;

function g_bb2_exo00_23_() {
  g_nargs = 0;
  return g_bb1_main();
}

g_bb2_exo00_23_.id = 1;
g_bb2_exo00_23_.parent = g_bb1_exo00_23_;


g_bb1_exo00_23_.ctrlpts = [g_bb1_exo00_23_,g_bb2_exo00_23_];


g_peps["exo00#"] = g_bb1_exo00_23_;
g_glo["exo00#"] = g_bb1_exo00_23_;

function g_bb1_document_2e_write() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_document_2e_write);
  }
  document.write(g_scm2host(g_r1));g_r1 = void 0;
  return g_r0;
}

g_bb1_document_2e_write.id = 0;
g_bb1_document_2e_write.parent = g_bb1_document_2e_write;
g_bb1_document_2e_write.nfree = -1;
g_bb1_document_2e_write._name = g_make_interned_symbol("document.write");
g_bb1_document_2e_write.ctrlpts = null;
g_bb1_document_2e_write.info = false;


g_bb1_document_2e_write.ctrlpts = [g_bb1_document_2e_write];


g_peps["document.write"] = g_bb1_document_2e_write;
g_glo["document.write"] = g_bb1_document_2e_write;

function g_bb1_main() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_main);
  }
  g_r1 = g_cst0_G_exo00;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_main);
  } else {
    g_nargs = 1;
    return g_bb1_document_2e_write();
  }
}

g_bb1_main.id = 0;
g_bb1_main.parent = g_bb1_main;
g_bb1_main.nfree = -1;
g_bb1_main._name = g_make_interned_symbol("main");
g_bb1_main.ctrlpts = null;
g_bb1_main.info = false;

function g_bb2_main() {
  g_nargs = 1;
  return g_bb1_document_2e_write();
}

g_bb2_main.id = 1;
g_bb2_main.parent = g_bb1_main;


g_bb1_main.ctrlpts = [g_bb1_main,g_bb2_main];


g_peps["main"] = g_bb1_main;
g_glo["main"] = g_bb1_main;

g_module_register([[g_make_interned_symbol("exo00")],[],null,1,g_bb1_exo00_23_,false]);

