// File generated by Gambit v4.9.3
// Link info: (409003 (js ()) "exo05" (("exo05")) (module_register glo char ffi pair make_interned_symbol ratnum cpxnum flonum make_interned_char peps poll pollcount string r1 r0 sp stack wrong_nargs nargs) () (comp? body-append-br log-obj body-append log-rat log-int log body-prepend-br int? body-append-text-br rat? log-str positive? log-char log-real num? log-comp log-bool float? exo05#) () #f)

var g_cst0_G_exo05 = new G_ScmString([85,110,32,112,114,101,109,105,101,114,32,116,101,120,116,32,97,118,101,99,32,108,105,110,101,32,98,114,101,97,107]);

var g_cst1_G_exo05 = new G_ScmString([101,116,32,117,110,32,115,101,99,111,110,100,32,115,97,110,115,32,108,105,110,101,32,98,114,101,97,107,46,32]);

var g_cst2_G_exo05 = new G_ScmString([106,101,32,116,101,32,118,111,108,101,32,108,97,32,112,108,97,99,101,32,100,117,32,112,114,101,109,115]);

var g_cst3_G_exo05 = new G_ScmString([99,101,99,105,32,101,115,116,32,100,117,32,60,98,62,116,101,120,116,32,111,110,108,121,60,47,98,62,44,32,108,101,115,32,116,97,103,115,32,110,101,32,109,97,114,99,104,101,110,116,32,112,97,115]);

var g_cst4_G_exo05 = new G_ScmString([60,100,105,118,32,105,100,61,39,114,101,100,45,115,113,117,97,114,101,39,32,115,116,121,108,101,61,39,98,97,99,107,103,114,111,117,110,100,58,114,101,100,59,104,101,105,103,104,116,58,51,48,48,112,120,59,119,105,100,116,104,58,51,48,48,112,120,39,62,60,47,100,105,118,62]);

var g_cst5_G_exo05 = new G_ScmString([115,116,97,114,116]);

var g_cst6_G_exo05 = new G_Pair(g_make_interned_char(99),new G_Pair(new G_ScmString([104,101,108,108,111]),new G_Pair(23,new G_Pair(new G_Flonum(3.14),new G_Pair(new G_Cpxnum(2,3),new G_Pair(new G_Ratnum(-22,7),new G_Pair(false,new G_Pair(new G_Pair(g_make_interned_symbol("DOM-body"),null),null))))))));

var g_cst20_G_exo05 = new G_ScmString([101,110,100]);

var g_cst21_G_exo05 = new G_ScmString([60,98,114,47,62]);

var g_cst22_G_exo05 = new G_ScmString([60,98,114,47,62]);

var g_cst23_G_exo05 = new G_ScmString([60,98,114,47,62]);

function g_bb1_exo05_23_() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_exo05_23_);
  }
  g_stack[g_sp+1] = g_r0;
  g_r1 = g_cst0_G_exo05;
  ++g_sp;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_exo05_23_);
  } else {
    g_r0 = g_bb3_exo05_23_;
    g_nargs = 1;
    return g_bb1_body_2d_append_2d_br();
  }
}

g_bb1_exo05_23_.id = 0;
g_bb1_exo05_23_.parent = g_bb1_exo05_23_;
g_bb1_exo05_23_.nfree = -1;
g_bb1_exo05_23_._name = g_make_interned_symbol("exo05#");
g_bb1_exo05_23_.ctrlpts = null;
g_bb1_exo05_23_.info = false;

function g_bb2_exo05_23_() {
  g_r0 = g_bb3_exo05_23_;
  g_nargs = 1;
  return g_bb1_body_2d_append_2d_br();
}

g_bb2_exo05_23_.id = 1;
g_bb2_exo05_23_.parent = g_bb1_exo05_23_;

function g_bb3_exo05_23_() { // return-point
  g_r1 = g_cst1_G_exo05;
  g_r0 = g_bb4_exo05_23_;
  g_nargs = 1;
  return g_bb1_body_2d_append();
}

g_bb3_exo05_23_.id = 2;
g_bb3_exo05_23_.parent = g_bb1_exo05_23_;
g_bb3_exo05_23_.fs = 1;
g_bb3_exo05_23_.link = 1;

function g_bb4_exo05_23_() { // return-point
  g_r1 = g_cst2_G_exo05;
  g_r0 = g_bb5_exo05_23_;
  g_nargs = 1;
  return g_bb1_body_2d_prepend_2d_br();
}

g_bb4_exo05_23_.id = 3;
g_bb4_exo05_23_.parent = g_bb1_exo05_23_;
g_bb4_exo05_23_.fs = 1;
g_bb4_exo05_23_.link = 1;

function g_bb5_exo05_23_() { // return-point
  g_r1 = g_cst3_G_exo05;
  g_r0 = g_bb6_exo05_23_;
  g_nargs = 1;
  return g_bb1_body_2d_append_2d_text_2d_br();
}

g_bb5_exo05_23_.id = 4;
g_bb5_exo05_23_.parent = g_bb1_exo05_23_;
g_bb5_exo05_23_.fs = 1;
g_bb5_exo05_23_.link = 1;

function g_bb6_exo05_23_() { // return-point
  g_r1 = g_cst4_G_exo05;
  g_r0 = g_bb7_exo05_23_;
  g_nargs = 1;
  return g_bb1_body_2d_append();
}

g_bb6_exo05_23_.id = 5;
g_bb6_exo05_23_.parent = g_bb1_exo05_23_;
g_bb6_exo05_23_.fs = 1;
g_bb6_exo05_23_.link = 1;

function g_bb7_exo05_23_() { // return-point
  g_r1 = g_cst5_G_exo05;
  g_r0 = g_bb8_exo05_23_;
  g_nargs = 1;
  return g_peps["log"]();
}

g_bb7_exo05_23_.id = 6;
g_bb7_exo05_23_.parent = g_bb1_exo05_23_;
g_bb7_exo05_23_.fs = 1;
g_bb7_exo05_23_.link = 1;

function g_bb8_exo05_23_() { // return-point
  g_r1 = g_cst6_G_exo05;
  g_r0 = g_bb19_exo05_23_;
  if (g_r1 instanceof G_Pair) {
    return g_bb12_exo05_23_();
  } else {
    return g_bb18_exo05_23_();
  }
}

g_bb8_exo05_23_.id = 7;
g_bb8_exo05_23_.parent = g_bb1_exo05_23_;
g_bb8_exo05_23_.fs = 1;
g_bb8_exo05_23_.link = 1;

function g_bb9_exo05_23_() {
  if (g_r1 instanceof G_Pair) {
    return g_bb12_exo05_23_();
  } else {
    return g_bb18_exo05_23_();
  }
}

g_bb9_exo05_23_.id = 8;
g_bb9_exo05_23_.parent = g_bb1_exo05_23_;

function g_bb19_exo05_23_() { // return-point
  g_r1 = g_cst20_G_exo05;
  g_r0 = g_stack[g_sp];
  if (--g_pollcount === 0) {
    return g_poll(g_bb20_exo05_23_);
  } else {
    g_nargs = 1;
    --g_sp;
    return g_peps["log"]();
  }
}

g_bb19_exo05_23_.id = 9;
g_bb19_exo05_23_.parent = g_bb1_exo05_23_;
g_bb19_exo05_23_.fs = 1;
g_bb19_exo05_23_.link = 1;

function g_bb12_exo05_23_() {
  g_stack[g_sp+1] = g_r0;
  g_stack[g_sp+2] = g_r1;
  g_r1 = g_r1.car;
  g_r0 = g_bb10_exo05_23_;
  g_sp += 2;
  if (--g_pollcount === 0) {
    return g_poll(g_bb13_exo05_23_);
  } else {
    g_stack[g_sp+1] = g_r0;
    ++g_sp;
    if (--g_pollcount === 0) {
      return g_poll(g_bb14_exo05_23_);
    } else {
      g_r0 = g_bb15_exo05_23_;
      g_nargs = 1;
      return g_bb1_num_3f_();
    }
  }
}

g_bb12_exo05_23_.id = 10;
g_bb12_exo05_23_.parent = g_bb1_exo05_23_;

function g_bb18_exo05_23_() {
  g_r1 = null;
  return g_r0;
}

g_bb18_exo05_23_.id = 11;
g_bb18_exo05_23_.parent = g_bb1_exo05_23_;

function g_bb20_exo05_23_() {
  g_nargs = 1;
  --g_sp;
  return g_peps["log"]();
}

g_bb20_exo05_23_.id = 12;
g_bb20_exo05_23_.parent = g_bb1_exo05_23_;

function g_bb13_exo05_23_() {
  g_stack[g_sp+1] = g_r0;
  ++g_sp;
  if (--g_pollcount === 0) {
    return g_poll(g_bb14_exo05_23_);
  } else {
    g_r0 = g_bb15_exo05_23_;
    g_nargs = 1;
    return g_bb1_num_3f_();
  }
}

g_bb13_exo05_23_.id = 13;
g_bb13_exo05_23_.parent = g_bb1_exo05_23_;

function g_bb10_exo05_23_() { // return-point
  g_stack[g_sp+1] = g_r1;
  g_r1 = g_stack[g_sp].cdr;
  g_r0 = g_bb17_exo05_23_;
  ++g_sp;
  if (g_r1 instanceof G_Pair) {
    return g_bb12_exo05_23_();
  } else {
    return g_bb18_exo05_23_();
  }
}

g_bb10_exo05_23_.id = 14;
g_bb10_exo05_23_.parent = g_bb1_exo05_23_;
g_bb10_exo05_23_.fs = 2;
g_bb10_exo05_23_.link = 1;

function g_bb14_exo05_23_() {
  g_r0 = g_bb15_exo05_23_;
  g_nargs = 1;
  return g_bb1_num_3f_();
}

g_bb14_exo05_23_.id = 15;
g_bb14_exo05_23_.parent = g_bb1_exo05_23_;

function g_bb15_exo05_23_() { // return-point
  g_r0 = g_stack[g_sp];
  if (--g_pollcount === 0) {
    return g_poll(g_bb16_exo05_23_);
  } else {
    g_nargs = 1;
    --g_sp;
    return g_bb1_log_2d_bool();
  }
}

g_bb15_exo05_23_.id = 16;
g_bb15_exo05_23_.parent = g_bb1_exo05_23_;
g_bb15_exo05_23_.fs = 1;
g_bb15_exo05_23_.link = 1;

function g_bb11_exo05_23_() {
  if (g_r1 instanceof G_Pair) {
    return g_bb12_exo05_23_();
  } else {
    return g_bb18_exo05_23_();
  }
}

g_bb11_exo05_23_.id = 17;
g_bb11_exo05_23_.parent = g_bb1_exo05_23_;

function g_bb17_exo05_23_() { // return-point
  g_r1 = new G_Pair(g_stack[g_sp],g_r1);
  g_sp -= 3;
  return g_stack[g_sp+1]();
}

g_bb17_exo05_23_.id = 18;
g_bb17_exo05_23_.parent = g_bb1_exo05_23_;
g_bb17_exo05_23_.fs = 3;
g_bb17_exo05_23_.link = 1;

function g_bb16_exo05_23_() {
  g_nargs = 1;
  --g_sp;
  return g_bb1_log_2d_bool();
}

g_bb16_exo05_23_.id = 19;
g_bb16_exo05_23_.parent = g_bb1_exo05_23_;


g_bb1_exo05_23_.ctrlpts = [g_bb1_exo05_23_,g_bb2_exo05_23_,g_bb3_exo05_23_,g_bb4_exo05_23_,g_bb5_exo05_23_,g_bb6_exo05_23_,g_bb7_exo05_23_,g_bb8_exo05_23_,g_bb9_exo05_23_,g_bb19_exo05_23_,g_bb12_exo05_23_,g_bb18_exo05_23_,g_bb20_exo05_23_,g_bb13_exo05_23_,g_bb10_exo05_23_,g_bb14_exo05_23_,g_bb15_exo05_23_,g_bb11_exo05_23_,g_bb17_exo05_23_,g_bb16_exo05_23_];


g_peps["exo05#"] = g_bb1_exo05_23_;
g_glo["exo05#"] = g_bb1_exo05_23_;

function g_bb1_int_3f_() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_int_3f_);
  }
  g_r1 = g_host2scm( Number.isInteger(g_r1) );
  return g_r0;
}

g_bb1_int_3f_.id = 0;
g_bb1_int_3f_.parent = g_bb1_int_3f_;
g_bb1_int_3f_.nfree = -1;
g_bb1_int_3f_._name = g_make_interned_symbol("int?");
g_bb1_int_3f_.ctrlpts = null;
g_bb1_int_3f_.info = false;


g_bb1_int_3f_.ctrlpts = [g_bb1_int_3f_];


g_peps["int?"] = g_bb1_int_3f_;
g_glo["int?"] = g_bb1_int_3f_;

function g_bb1_float_3f_() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_float_3f_);
  }
  g_r1 = JSON.stringify(Object.keys(g_r1)) === JSON.stringify(["val"]);
  return g_r0;
}

g_bb1_float_3f_.id = 0;
g_bb1_float_3f_.parent = g_bb1_float_3f_;
g_bb1_float_3f_.nfree = -1;
g_bb1_float_3f_._name = g_make_interned_symbol("float?");
g_bb1_float_3f_.ctrlpts = null;
g_bb1_float_3f_.info = false;


g_bb1_float_3f_.ctrlpts = [g_bb1_float_3f_];


g_peps["float?"] = g_bb1_float_3f_;
g_glo["float?"] = g_bb1_float_3f_;

function g_bb1_comp_3f_() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_comp_3f_);
  }
  g_r1 = JSON.stringify(Object.keys(g_r1)) === JSON.stringify(["real","imag"]);
  return g_r0;
}

g_bb1_comp_3f_.id = 0;
g_bb1_comp_3f_.parent = g_bb1_comp_3f_;
g_bb1_comp_3f_.nfree = -1;
g_bb1_comp_3f_._name = g_make_interned_symbol("comp?");
g_bb1_comp_3f_.ctrlpts = null;
g_bb1_comp_3f_.info = false;


g_bb1_comp_3f_.ctrlpts = [g_bb1_comp_3f_];


g_peps["comp?"] = g_bb1_comp_3f_;
g_glo["comp?"] = g_bb1_comp_3f_;

function g_bb1_rat_3f_() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_rat_3f_);
  }
  g_r1 = JSON.stringify(Object.keys(g_r1)) === JSON.stringify(["num","den"]);
  return g_r0;
}

g_bb1_rat_3f_.id = 0;
g_bb1_rat_3f_.parent = g_bb1_rat_3f_;
g_bb1_rat_3f_.nfree = -1;
g_bb1_rat_3f_._name = g_make_interned_symbol("rat?");
g_bb1_rat_3f_.ctrlpts = null;
g_bb1_rat_3f_.info = false;


g_bb1_rat_3f_.ctrlpts = [g_bb1_rat_3f_];


g_peps["rat?"] = g_bb1_rat_3f_;
g_glo["rat?"] = g_bb1_rat_3f_;

function g_bb1_num_3f_() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_num_3f_);
  }
  g_stack[g_sp+1] = g_r0;
  g_stack[g_sp+2] = g_r1;
  g_sp += 2;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_num_3f_);
  } else {
    g_r0 = g_bb3_num_3f_;
    g_nargs = 1;
    return g_bb1_int_3f_();
  }
}

g_bb1_num_3f_.id = 0;
g_bb1_num_3f_.parent = g_bb1_num_3f_;
g_bb1_num_3f_.nfree = -1;
g_bb1_num_3f_._name = g_make_interned_symbol("num?");
g_bb1_num_3f_.ctrlpts = null;
g_bb1_num_3f_.info = false;

function g_bb2_num_3f_() {
  g_r0 = g_bb3_num_3f_;
  g_nargs = 1;
  return g_bb1_int_3f_();
}

g_bb2_num_3f_.id = 1;
g_bb2_num_3f_.parent = g_bb1_num_3f_;

function g_bb3_num_3f_() { // return-point
  if (!(g_r1 === false)) {
    g_sp -= 2;
    return g_stack[g_sp+1]();
  } else {
    g_r1 = g_stack[g_sp];
    g_r0 = g_bb5_num_3f_;
    g_nargs = 1;
    return g_bb1_float_3f_();
  }
}

g_bb3_num_3f_.id = 2;
g_bb3_num_3f_.parent = g_bb1_num_3f_;
g_bb3_num_3f_.fs = 2;
g_bb3_num_3f_.link = 1;

function g_bb10_num_3f_() {
  g_sp -= 2;
  return g_stack[g_sp+1]();
}

g_bb10_num_3f_.id = 3;
g_bb10_num_3f_.parent = g_bb1_num_3f_;

function g_bb4_num_3f_() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_bb5_num_3f_;
  g_nargs = 1;
  return g_bb1_float_3f_();
}

g_bb4_num_3f_.id = 4;
g_bb4_num_3f_.parent = g_bb1_num_3f_;

function g_bb5_num_3f_() { // return-point
  if (!(g_r1 === false)) {
    g_sp -= 2;
    return g_stack[g_sp+1]();
  } else {
    g_r1 = g_stack[g_sp];
    g_r0 = g_bb7_num_3f_;
    g_nargs = 1;
    return g_bb1_comp_3f_();
  }
}

g_bb5_num_3f_.id = 5;
g_bb5_num_3f_.parent = g_bb1_num_3f_;
g_bb5_num_3f_.fs = 2;
g_bb5_num_3f_.link = 1;

function g_bb6_num_3f_() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_bb7_num_3f_;
  g_nargs = 1;
  return g_bb1_comp_3f_();
}

g_bb6_num_3f_.id = 6;
g_bb6_num_3f_.parent = g_bb1_num_3f_;

function g_bb7_num_3f_() { // return-point
  if (!(g_r1 === false)) {
    g_sp -= 2;
    return g_stack[g_sp+1]();
  } else {
    g_r1 = g_stack[g_sp];
    g_r0 = g_stack[g_sp-1];
    if (--g_pollcount === 0) {
      return g_poll(g_bb9_num_3f_);
    } else {
      g_nargs = 1;
      g_sp -= 2;
      return g_bb1_rat_3f_();
    }
  }
}

g_bb7_num_3f_.id = 7;
g_bb7_num_3f_.parent = g_bb1_num_3f_;
g_bb7_num_3f_.fs = 2;
g_bb7_num_3f_.link = 1;

function g_bb8_num_3f_() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_stack[g_sp-1];
  if (--g_pollcount === 0) {
    return g_poll(g_bb9_num_3f_);
  } else {
    g_nargs = 1;
    g_sp -= 2;
    return g_bb1_rat_3f_();
  }
}

g_bb8_num_3f_.id = 8;
g_bb8_num_3f_.parent = g_bb1_num_3f_;

function g_bb9_num_3f_() {
  g_nargs = 1;
  g_sp -= 2;
  return g_bb1_rat_3f_();
}

g_bb9_num_3f_.id = 9;
g_bb9_num_3f_.parent = g_bb1_num_3f_;


g_bb1_num_3f_.ctrlpts = [g_bb1_num_3f_,g_bb2_num_3f_,g_bb3_num_3f_,g_bb10_num_3f_,g_bb4_num_3f_,g_bb5_num_3f_,g_bb6_num_3f_,g_bb7_num_3f_,g_bb8_num_3f_,g_bb9_num_3f_];


g_peps["num?"] = g_bb1_num_3f_;
g_glo["num?"] = g_bb1_num_3f_;

function g_bb1_positive_3f_() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_positive_3f_);
  }
  g_r1 = g_host2scm(g_r1 > 0);
  return g_r0;
}

g_bb1_positive_3f_.id = 0;
g_bb1_positive_3f_.parent = g_bb1_positive_3f_;
g_bb1_positive_3f_.nfree = -1;
g_bb1_positive_3f_._name = g_make_interned_symbol("positive?");
g_bb1_positive_3f_.ctrlpts = null;
g_bb1_positive_3f_.info = false;


g_bb1_positive_3f_.ctrlpts = [g_bb1_positive_3f_];


g_peps["positive?"] = g_bb1_positive_3f_;
g_glo["positive?"] = g_bb1_positive_3f_;

function g_bb1_log_2d_str() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_log_2d_str);
  }
  console.log(g_scm2host(g_r1));g_r1 = void 0;
  return g_r0;
}

g_bb1_log_2d_str.id = 0;
g_bb1_log_2d_str.parent = g_bb1_log_2d_str;
g_bb1_log_2d_str.nfree = -1;
g_bb1_log_2d_str._name = g_make_interned_symbol("log-str");
g_bb1_log_2d_str.ctrlpts = null;
g_bb1_log_2d_str.info = false;


g_bb1_log_2d_str.ctrlpts = [g_bb1_log_2d_str];


g_peps["log-str"] = g_bb1_log_2d_str;
g_glo["log-str"] = g_bb1_log_2d_str;

function g_bb1_log_2d_int() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_log_2d_int);
  }
  console.log(g_scm2host(g_r1));g_r1 = void 0;
  return g_r0;
}

g_bb1_log_2d_int.id = 0;
g_bb1_log_2d_int.parent = g_bb1_log_2d_int;
g_bb1_log_2d_int.nfree = -1;
g_bb1_log_2d_int._name = g_make_interned_symbol("log-int");
g_bb1_log_2d_int.ctrlpts = null;
g_bb1_log_2d_int.info = false;


g_bb1_log_2d_int.ctrlpts = [g_bb1_log_2d_int];


g_peps["log-int"] = g_bb1_log_2d_int;
g_glo["log-int"] = g_bb1_log_2d_int;

function g_bb1_log_2d_bool() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_log_2d_bool);
  }
  console.log(g_r1);g_r1 = void 0;
  return g_r0;
}

g_bb1_log_2d_bool.id = 0;
g_bb1_log_2d_bool.parent = g_bb1_log_2d_bool;
g_bb1_log_2d_bool.nfree = -1;
g_bb1_log_2d_bool._name = g_make_interned_symbol("log-bool");
g_bb1_log_2d_bool.ctrlpts = null;
g_bb1_log_2d_bool.info = false;


g_bb1_log_2d_bool.ctrlpts = [g_bb1_log_2d_bool];


g_peps["log-bool"] = g_bb1_log_2d_bool;
g_glo["log-bool"] = g_bb1_log_2d_bool;

function g_bb1_log_2d_char() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_log_2d_char);
  }
  console.log( String.fromCharCode(g_r1.code) );g_r1 = void 0;
  return g_r0;
}

g_bb1_log_2d_char.id = 0;
g_bb1_log_2d_char.parent = g_bb1_log_2d_char;
g_bb1_log_2d_char.nfree = -1;
g_bb1_log_2d_char._name = g_make_interned_symbol("log-char");
g_bb1_log_2d_char.ctrlpts = null;
g_bb1_log_2d_char.info = false;


g_bb1_log_2d_char.ctrlpts = [g_bb1_log_2d_char];


g_peps["log-char"] = g_bb1_log_2d_char;
g_glo["log-char"] = g_bb1_log_2d_char;

function g_bb1_log_2d_real() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_log_2d_real);
  }
  console.log(g_scm2host(g_r1));g_r1 = void 0;
  return g_r0;
}

g_bb1_log_2d_real.id = 0;
g_bb1_log_2d_real.parent = g_bb1_log_2d_real;
g_bb1_log_2d_real.nfree = -1;
g_bb1_log_2d_real._name = g_make_interned_symbol("log-real");
g_bb1_log_2d_real.ctrlpts = null;
g_bb1_log_2d_real.info = false;


g_bb1_log_2d_real.ctrlpts = [g_bb1_log_2d_real];


g_peps["log-real"] = g_bb1_log_2d_real;
g_glo["log-real"] = g_bb1_log_2d_real;

function g_bb1_log_2d_rat() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_log_2d_rat);
  }
  console.log( g_r1.num+"/"+g_r1.den );g_r1 = void 0;
  return g_r0;
}

g_bb1_log_2d_rat.id = 0;
g_bb1_log_2d_rat.parent = g_bb1_log_2d_rat;
g_bb1_log_2d_rat.nfree = -1;
g_bb1_log_2d_rat._name = g_make_interned_symbol("log-rat");
g_bb1_log_2d_rat.ctrlpts = null;
g_bb1_log_2d_rat.info = false;


g_bb1_log_2d_rat.ctrlpts = [g_bb1_log_2d_rat];


g_peps["log-rat"] = g_bb1_log_2d_rat;
g_glo["log-rat"] = g_bb1_log_2d_rat;

function g_bb1_log_2d_comp() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_log_2d_comp);
  }
  g_stack[g_sp+1] = g_r0;
  g_stack[g_sp+2] = g_r1;
  if (g_r1 instanceof G_Cpxnum) {
    g_sp += 2;
    g_r1 = g_r1.imag;
    g_r0 = g_bb3_log_2d_comp;
    g_nargs = 1;
    return g_peps["positive?"]();
  } else {
    g_sp += 2;
    g_r0 = g_bb7_log_2d_comp;
    g_nargs = 1;
    return g_peps["imag-part"]();
  }
}

g_bb1_log_2d_comp.id = 0;
g_bb1_log_2d_comp.parent = g_bb1_log_2d_comp;
g_bb1_log_2d_comp.nfree = -1;
g_bb1_log_2d_comp._name = g_make_interned_symbol("log-comp");
g_bb1_log_2d_comp.ctrlpts = null;
g_bb1_log_2d_comp.info = false;

function g_bb2_log_2d_comp() {
  g_r1 = g_r1.imag;
  g_r0 = g_bb3_log_2d_comp;
  g_nargs = 1;
  return g_peps["positive?"]();
}

g_bb2_log_2d_comp.id = 1;
g_bb2_log_2d_comp.parent = g_bb1_log_2d_comp;

function g_bb3_log_2d_comp() { // return-point
  if (!(g_r1 === false)) {
    console.log( g_stack[g_sp].real+"+"+g_stack[g_sp].imag+"i" );g_r1 = void 0;
    g_sp -= 2;
    return g_stack[g_sp+1]();
  } else {
    console.log( g_stack[g_sp].real.toString()+g_stack[g_sp].imag.toString()+"i" );g_r1 = void 0;
    g_sp -= 2;
    return g_stack[g_sp+1]();
  }
}

g_bb3_log_2d_comp.id = 2;
g_bb3_log_2d_comp.parent = g_bb1_log_2d_comp;
g_bb3_log_2d_comp.fs = 2;
g_bb3_log_2d_comp.link = 1;

function g_bb6_log_2d_comp() {
  g_r0 = g_bb7_log_2d_comp;
  g_nargs = 1;
  return g_peps["imag-part"]();
}

g_bb6_log_2d_comp.id = 3;
g_bb6_log_2d_comp.parent = g_bb1_log_2d_comp;

function g_bb7_log_2d_comp() { // return-point
  g_r0 = g_bb3_log_2d_comp;
  g_nargs = 1;
  return g_peps["positive?"]();
}

g_bb7_log_2d_comp.id = 4;
g_bb7_log_2d_comp.parent = g_bb1_log_2d_comp;
g_bb7_log_2d_comp.fs = 2;
g_bb7_log_2d_comp.link = 1;

function g_bb4_log_2d_comp() {
  console.log( g_stack[g_sp].real+"+"+g_stack[g_sp].imag+"i" );g_r1 = void 0;
  g_sp -= 2;
  return g_stack[g_sp+1]();
}

g_bb4_log_2d_comp.id = 5;
g_bb4_log_2d_comp.parent = g_bb1_log_2d_comp;

function g_bb5_log_2d_comp() {
  console.log( g_stack[g_sp].real.toString()+g_stack[g_sp].imag.toString()+"i" );g_r1 = void 0;
  g_sp -= 2;
  return g_stack[g_sp+1]();
}

g_bb5_log_2d_comp.id = 6;
g_bb5_log_2d_comp.parent = g_bb1_log_2d_comp;


g_bb1_log_2d_comp.ctrlpts = [g_bb1_log_2d_comp,g_bb2_log_2d_comp,g_bb3_log_2d_comp,g_bb6_log_2d_comp,g_bb7_log_2d_comp,g_bb4_log_2d_comp,g_bb5_log_2d_comp];


g_peps["log-comp"] = g_bb1_log_2d_comp;
g_glo["log-comp"] = g_bb1_log_2d_comp;

function g_bb1_log_2d_obj() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_log_2d_obj);
  }
  console.log(g_r1);g_r1 = void 0;
  return g_r0;
}

g_bb1_log_2d_obj.id = 0;
g_bb1_log_2d_obj.parent = g_bb1_log_2d_obj;
g_bb1_log_2d_obj.nfree = -1;
g_bb1_log_2d_obj._name = g_make_interned_symbol("log-obj");
g_bb1_log_2d_obj.ctrlpts = null;
g_bb1_log_2d_obj.info = false;


g_bb1_log_2d_obj.ctrlpts = [g_bb1_log_2d_obj];


g_peps["log-obj"] = g_bb1_log_2d_obj;
g_glo["log-obj"] = g_bb1_log_2d_obj;

function g_bb1_log() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_log);
  }
  if (g_r1 instanceof G_ScmString) {
    if (--g_pollcount === 0) {
      return g_poll(g_bb3_log);
    } else {
      g_nargs = 1;
      return g_bb1_log_2d_str();
    }
  } else {
    if (typeof g_r1 === "number") {
      if (--g_pollcount === 0) {
        return g_poll(g_bb8_log);
      } else {
        g_nargs = 1;
        return g_bb1_log_2d_int();
      }
    } else {
      g_stack[g_sp+1] = g_r0;
      g_stack[g_sp+2] = g_r1;
      g_r0 = g_bb6_log;
      g_nargs = 1;
      g_sp += 2;
      return g_peps["##integer?"]();
    }
  }
}

g_bb1_log.id = 0;
g_bb1_log.parent = g_bb1_log;
g_bb1_log.nfree = -1;
g_bb1_log._name = g_make_interned_symbol("log");
g_bb1_log.ctrlpts = null;
g_bb1_log.info = false;

function g_bb2_log() {
  if (--g_pollcount === 0) {
    return g_poll(g_bb3_log);
  } else {
    g_nargs = 1;
    return g_bb1_log_2d_str();
  }
}

g_bb2_log.id = 1;
g_bb2_log.parent = g_bb1_log;

function g_bb3_log() {
  g_nargs = 1;
  return g_bb1_log_2d_str();
}

g_bb3_log.id = 2;
g_bb3_log.parent = g_bb1_log;

function g_bb4_log() {
  if (typeof g_r1 === "number") {
    if (--g_pollcount === 0) {
      return g_poll(g_bb8_log);
    } else {
      g_nargs = 1;
      return g_bb1_log_2d_int();
    }
  } else {
    g_stack[g_sp+1] = g_r0;
    g_stack[g_sp+2] = g_r1;
    g_r0 = g_bb6_log;
    g_nargs = 1;
    g_sp += 2;
    return g_peps["##integer?"]();
  }
}

g_bb4_log.id = 3;
g_bb4_log.parent = g_bb1_log;

function g_bb5_log() {
  if (--g_pollcount === 0) {
    return g_poll(g_bb8_log);
  } else {
    g_nargs = 1;
    return g_bb1_log_2d_int();
  }
}

g_bb5_log.id = 4;
g_bb5_log.parent = g_bb1_log;

function g_bb8_log() {
  g_nargs = 1;
  return g_bb1_log_2d_int();
}

g_bb8_log.id = 5;
g_bb8_log.parent = g_bb1_log;

function g_bb31_log() {
  g_stack[g_sp+1] = g_r0;
  g_stack[g_sp+2] = g_r1;
  g_r0 = g_bb6_log;
  g_nargs = 1;
  g_sp += 2;
  return g_peps["##integer?"]();
}

g_bb31_log.id = 6;
g_bb31_log.parent = g_bb1_log;

function g_bb6_log() { // return-point
  if (!(g_r1 === false)) {
    g_r1 = g_stack[g_sp];
    g_r0 = g_stack[g_sp-1];
    g_sp -= 2;
    if (--g_pollcount === 0) {
      return g_poll(g_bb8_log);
    } else {
      g_nargs = 1;
      return g_bb1_log_2d_int();
    }
  } else {
    if (typeof g_stack[g_sp] === "number") {
      return g_bb11_log();
    } else {
      if (g_stack[g_sp] instanceof G_Flonum) {
        return g_bb11_log();
      } else {
        g_r1 = g_stack[g_sp];
        g_r0 = g_bb10_log;
        g_nargs = 1;
        return g_peps["##real?"]();
      }
    }
  }
}

g_bb6_log.id = 7;
g_bb6_log.parent = g_bb1_log;
g_bb6_log.fs = 2;
g_bb6_log.link = 1;

function g_bb7_log() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_stack[g_sp-1];
  g_sp -= 2;
  if (--g_pollcount === 0) {
    return g_poll(g_bb8_log);
  } else {
    g_nargs = 1;
    return g_bb1_log_2d_int();
  }
}

g_bb7_log.id = 8;
g_bb7_log.parent = g_bb1_log;

function g_bb9_log() {
  if (typeof g_stack[g_sp] === "number") {
    return g_bb11_log();
  } else {
    if (g_stack[g_sp] instanceof G_Flonum) {
      return g_bb11_log();
    } else {
      g_r1 = g_stack[g_sp];
      g_r0 = g_bb10_log;
      g_nargs = 1;
      return g_peps["##real?"]();
    }
  }
}

g_bb9_log.id = 9;
g_bb9_log.parent = g_bb1_log;

function g_bb11_log() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_stack[g_sp-1];
  if (--g_pollcount === 0) {
    return g_poll(g_bb12_log);
  } else {
    g_nargs = 1;
    g_sp -= 2;
    return g_bb1_log_2d_real();
  }
}

g_bb11_log.id = 10;
g_bb11_log.parent = g_bb1_log;

function g_bb29_log() {
  if (g_stack[g_sp] instanceof G_Flonum) {
    return g_bb11_log();
  } else {
    g_r1 = g_stack[g_sp];
    g_r0 = g_bb10_log;
    g_nargs = 1;
    return g_peps["##real?"]();
  }
}

g_bb29_log.id = 11;
g_bb29_log.parent = g_bb1_log;

function g_bb30_log() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_bb10_log;
  g_nargs = 1;
  return g_peps["##real?"]();
}

g_bb30_log.id = 12;
g_bb30_log.parent = g_bb1_log;

function g_bb10_log() { // return-point
  if (!(g_r1 === false)) {
    return g_bb11_log();
  } else {
    if (typeof g_stack[g_sp] === "number") {
      return g_bb15_log();
    } else {
      if (g_stack[g_sp] instanceof G_Flonum) {
        if (g_stack[g_sp].val >= -1.7976931348623151e308 && g_stack[g_sp].val <= 1.7976931348623151e308) {
          return g_bb15_log();
        } else {
          if (g_stack[g_sp] instanceof G_Char) {
            return g_bb20_log();
          } else {
            return g_bb22_log();
          }
        }
      } else {
        g_r1 = g_stack[g_sp];
        g_r0 = g_bb14_log;
        g_nargs = 1;
        return g_peps["##rational?"]();
      }
    }
  }
}

g_bb10_log.id = 13;
g_bb10_log.parent = g_bb1_log;
g_bb10_log.fs = 2;
g_bb10_log.link = 1;

function g_bb12_log() {
  g_nargs = 1;
  g_sp -= 2;
  return g_bb1_log_2d_real();
}

g_bb12_log.id = 14;
g_bb12_log.parent = g_bb1_log;

function g_bb13_log() {
  if (typeof g_stack[g_sp] === "number") {
    return g_bb15_log();
  } else {
    if (g_stack[g_sp] instanceof G_Flonum) {
      if (g_stack[g_sp].val >= -1.7976931348623151e308 && g_stack[g_sp].val <= 1.7976931348623151e308) {
        return g_bb15_log();
      } else {
        if (g_stack[g_sp] instanceof G_Char) {
          return g_bb20_log();
        } else {
          return g_bb22_log();
        }
      }
    } else {
      g_r1 = g_stack[g_sp];
      g_r0 = g_bb14_log;
      g_nargs = 1;
      return g_peps["##rational?"]();
    }
  }
}

g_bb13_log.id = 15;
g_bb13_log.parent = g_bb1_log;

function g_bb15_log() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_stack[g_sp-1];
  if (--g_pollcount === 0) {
    return g_poll(g_bb16_log);
  } else {
    g_nargs = 1;
    g_sp -= 2;
    return g_bb1_log_2d_rat();
  }
}

g_bb15_log.id = 16;
g_bb15_log.parent = g_bb1_log;

function g_bb17_log() {
  if (g_stack[g_sp] instanceof G_Flonum) {
    if (g_stack[g_sp].val >= -1.7976931348623151e308 && g_stack[g_sp].val <= 1.7976931348623151e308) {
      return g_bb15_log();
    } else {
      if (g_stack[g_sp] instanceof G_Char) {
        return g_bb20_log();
      } else {
        return g_bb22_log();
      }
    }
  } else {
    g_r1 = g_stack[g_sp];
    g_r0 = g_bb14_log;
    g_nargs = 1;
    return g_peps["##rational?"]();
  }
}

g_bb17_log.id = 17;
g_bb17_log.parent = g_bb1_log;

function g_bb18_log() {
  if (g_stack[g_sp].val >= -1.7976931348623151e308 && g_stack[g_sp].val <= 1.7976931348623151e308) {
    return g_bb15_log();
  } else {
    if (g_stack[g_sp] instanceof G_Char) {
      return g_bb20_log();
    } else {
      return g_bb22_log();
    }
  }
}

g_bb18_log.id = 18;
g_bb18_log.parent = g_bb1_log;

function g_bb19_log() {
  if (g_stack[g_sp] instanceof G_Char) {
    g_r1 = g_stack[g_sp];
    g_r0 = g_stack[g_sp-1];
    if (--g_pollcount === 0) {
      return g_poll(g_bb21_log);
    } else {
      g_nargs = 1;
      g_sp -= 2;
      return g_bb1_log_2d_char();
    }
  } else {
    g_r1 = g_stack[g_sp];
    g_r0 = g_bb23_log;
    g_nargs = 1;
    return g_peps["##complex?"]();
  }
}

g_bb19_log.id = 19;
g_bb19_log.parent = g_bb1_log;

function g_bb20_log() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_stack[g_sp-1];
  if (--g_pollcount === 0) {
    return g_poll(g_bb21_log);
  } else {
    g_nargs = 1;
    g_sp -= 2;
    return g_bb1_log_2d_char();
  }
}

g_bb20_log.id = 20;
g_bb20_log.parent = g_bb1_log;

function g_bb22_log() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_bb23_log;
  g_nargs = 1;
  return g_peps["##complex?"]();
}

g_bb22_log.id = 21;
g_bb22_log.parent = g_bb1_log;

function g_bb28_log() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_bb14_log;
  g_nargs = 1;
  return g_peps["##rational?"]();
}

g_bb28_log.id = 22;
g_bb28_log.parent = g_bb1_log;

function g_bb14_log() { // return-point
  if (!(g_r1 === false)) {
    return g_bb15_log();
  } else {
    if (g_stack[g_sp] instanceof G_Char) {
      return g_bb20_log();
    } else {
      return g_bb22_log();
    }
  }
}

g_bb14_log.id = 23;
g_bb14_log.parent = g_bb1_log;
g_bb14_log.fs = 2;
g_bb14_log.link = 1;

function g_bb16_log() {
  g_nargs = 1;
  g_sp -= 2;
  return g_bb1_log_2d_rat();
}

g_bb16_log.id = 24;
g_bb16_log.parent = g_bb1_log;

function g_bb21_log() {
  g_nargs = 1;
  g_sp -= 2;
  return g_bb1_log_2d_char();
}

g_bb21_log.id = 25;
g_bb21_log.parent = g_bb1_log;

function g_bb23_log() { // return-point
  if (!(g_r1 === false)) {
    g_r1 = g_stack[g_sp];
    g_r0 = g_stack[g_sp-1];
    if (--g_pollcount === 0) {
      return g_poll(g_bb25_log);
    } else {
      g_nargs = 1;
      g_sp -= 2;
      return g_bb1_log_2d_comp();
    }
  } else {
    g_r1 = g_stack[g_sp];
    g_r0 = g_stack[g_sp-1];
    if (--g_pollcount === 0) {
      return g_poll(g_bb27_log);
    } else {
      g_nargs = 1;
      g_sp -= 2;
      return g_bb1_log_2d_obj();
    }
  }
}

g_bb23_log.id = 26;
g_bb23_log.parent = g_bb1_log;
g_bb23_log.fs = 2;
g_bb23_log.link = 1;

function g_bb24_log() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_stack[g_sp-1];
  if (--g_pollcount === 0) {
    return g_poll(g_bb25_log);
  } else {
    g_nargs = 1;
    g_sp -= 2;
    return g_bb1_log_2d_comp();
  }
}

g_bb24_log.id = 27;
g_bb24_log.parent = g_bb1_log;

function g_bb25_log() {
  g_nargs = 1;
  g_sp -= 2;
  return g_bb1_log_2d_comp();
}

g_bb25_log.id = 28;
g_bb25_log.parent = g_bb1_log;

function g_bb26_log() {
  g_r1 = g_stack[g_sp];
  g_r0 = g_stack[g_sp-1];
  if (--g_pollcount === 0) {
    return g_poll(g_bb27_log);
  } else {
    g_nargs = 1;
    g_sp -= 2;
    return g_bb1_log_2d_obj();
  }
}

g_bb26_log.id = 29;
g_bb26_log.parent = g_bb1_log;

function g_bb27_log() {
  g_nargs = 1;
  g_sp -= 2;
  return g_bb1_log_2d_obj();
}

g_bb27_log.id = 30;
g_bb27_log.parent = g_bb1_log;


g_bb1_log.ctrlpts = [g_bb1_log,g_bb2_log,g_bb3_log,g_bb4_log,g_bb5_log,g_bb8_log,g_bb31_log,g_bb6_log,g_bb7_log,g_bb9_log,g_bb11_log,g_bb29_log,g_bb30_log,g_bb10_log,g_bb12_log,g_bb13_log,g_bb15_log,g_bb17_log,g_bb18_log,g_bb19_log,g_bb20_log,g_bb22_log,g_bb28_log,g_bb14_log,g_bb16_log,g_bb21_log,g_bb23_log,g_bb24_log,g_bb25_log,g_bb26_log,g_bb27_log];


g_peps["log"] = g_bb1_log;
g_glo["log"] = g_bb1_log;

function g_bb1_body_2d_prepend_2d_br() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_body_2d_prepend_2d_br);
  }
  body.innerHTML = g_scm2host(g_r1) + g_scm2host(g_cst21_G_exo05) + body.innerHTML;g_r1 = void 0;
  return g_r0;
}

g_bb1_body_2d_prepend_2d_br.id = 0;
g_bb1_body_2d_prepend_2d_br.parent = g_bb1_body_2d_prepend_2d_br;
g_bb1_body_2d_prepend_2d_br.nfree = -1;
g_bb1_body_2d_prepend_2d_br._name = g_make_interned_symbol("body-prepend-br");
g_bb1_body_2d_prepend_2d_br.ctrlpts = null;
g_bb1_body_2d_prepend_2d_br.info = false;


g_bb1_body_2d_prepend_2d_br.ctrlpts = [g_bb1_body_2d_prepend_2d_br];


g_peps["body-prepend-br"] = g_bb1_body_2d_prepend_2d_br;
g_glo["body-prepend-br"] = g_bb1_body_2d_prepend_2d_br;

function g_bb1_body_2d_append() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_body_2d_append);
  }
  body.innerHTML += g_scm2host(g_r1);g_r1 = void 0;
  return g_r0;
}

g_bb1_body_2d_append.id = 0;
g_bb1_body_2d_append.parent = g_bb1_body_2d_append;
g_bb1_body_2d_append.nfree = -1;
g_bb1_body_2d_append._name = g_make_interned_symbol("body-append");
g_bb1_body_2d_append.ctrlpts = null;
g_bb1_body_2d_append.info = false;


g_bb1_body_2d_append.ctrlpts = [g_bb1_body_2d_append];


g_peps["body-append"] = g_bb1_body_2d_append;
g_glo["body-append"] = g_bb1_body_2d_append;

function g_bb1_body_2d_append_2d_br() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_body_2d_append_2d_br);
  }
  body.innerHTML+= g_scm2host(g_r1) + g_scm2host(g_cst22_G_exo05);g_r1 = void 0;
  return g_r0;
}

g_bb1_body_2d_append_2d_br.id = 0;
g_bb1_body_2d_append_2d_br.parent = g_bb1_body_2d_append_2d_br;
g_bb1_body_2d_append_2d_br.nfree = -1;
g_bb1_body_2d_append_2d_br._name = g_make_interned_symbol("body-append-br");
g_bb1_body_2d_append_2d_br.ctrlpts = null;
g_bb1_body_2d_append_2d_br.info = false;


g_bb1_body_2d_append_2d_br.ctrlpts = [g_bb1_body_2d_append_2d_br];


g_peps["body-append-br"] = g_bb1_body_2d_append_2d_br;
g_glo["body-append-br"] = g_bb1_body_2d_append_2d_br;

function g_bb1_body_2d_append_2d_text_2d_br() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_body_2d_append_2d_text_2d_br);
  }
  body.append(g_scm2host(g_r1));g_r1 = g_cst23_G_exo05;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_body_2d_append_2d_text_2d_br);
  } else {
    g_nargs = 1;
    return g_bb1_body_2d_append();
  }
}

g_bb1_body_2d_append_2d_text_2d_br.id = 0;
g_bb1_body_2d_append_2d_text_2d_br.parent = g_bb1_body_2d_append_2d_text_2d_br;
g_bb1_body_2d_append_2d_text_2d_br.nfree = -1;
g_bb1_body_2d_append_2d_text_2d_br._name = g_make_interned_symbol("body-append-text-br");
g_bb1_body_2d_append_2d_text_2d_br.ctrlpts = null;
g_bb1_body_2d_append_2d_text_2d_br.info = false;

function g_bb2_body_2d_append_2d_text_2d_br() {
  g_nargs = 1;
  return g_bb1_body_2d_append();
}

g_bb2_body_2d_append_2d_text_2d_br.id = 1;
g_bb2_body_2d_append_2d_text_2d_br.parent = g_bb1_body_2d_append_2d_text_2d_br;


g_bb1_body_2d_append_2d_text_2d_br.ctrlpts = [g_bb1_body_2d_append_2d_text_2d_br,g_bb2_body_2d_append_2d_text_2d_br];


g_peps["body-append-text-br"] = g_bb1_body_2d_append_2d_text_2d_br;
g_glo["body-append-text-br"] = g_bb1_body_2d_append_2d_text_2d_br;

g_module_register([[g_make_interned_symbol("exo05")],[],null,1,g_bb1_exo05_23_,false]);

