// File generated by Gambit v4.9.3
// Link info: (409003 (js ()) "exo04" (("exo04")) (module_register glo make_interned_symbol r3 build_rest peps sp stack r2 ffi string r0 pair r1 poll pollcount wrong_nargs nargs) () (string-append-2 main exo04# car error string-append-multiarg cdr log string-append-list) () #f)

var g_cst0_G_exo04 = new G_ScmString([99,97,114,32,101,120,112,101,99,116,115,32,97,32,112,97,105,114]);

var g_cst1_G_exo04 = new G_ScmString([99,100,114,32,101,120,112,101,99,116,115,32,97,32,112,97,105,114]);

var g_cst2_G_exo04 = new G_ScmString([]);

var g_cst3_G_exo04 = new G_ScmString([]);

var g_cst4_G_exo04 = new G_ScmString([119,111,114,108,100,32,33]);

var g_cst5_G_exo04 = new G_ScmString([104,101,108,108,111,32]);

var g_cst6_G_exo04 = new G_Pair(new G_ScmString([104,101,108,108,111]),new G_Pair(new G_ScmString([119,111,114,108,100,32,33]),new G_Pair(new G_ScmString([111,110,32,112,101,117,116,32,109,101,116,116,114,101]),new G_Pair(new G_ScmString([97,117,116,97,110,116,32,100,39,97,114,103,117,109,101,110,116]),new G_Pair(new G_ScmString([113,117,39,111,110,32,118,101,117,116,32,60,51]),null)))));

var g_cst16_G_exo04 = new G_ScmString([104,101,108,108,111]);

var g_cst17_G_exo04 = new G_ScmString([119,111,114,108,100,32,33]);

var g_cst18_G_exo04 = new G_ScmString([111,110,32,112,101,117,116,32,109,101,116,116,114,101]);

var g_cst19_G_exo04 = new G_ScmString([97,117,116,97,110,116,32,100,39,97,114,103,117,109,101,110,116]);

var g_cst20_G_exo04 = new G_ScmString([32,100,101,32,108,105,115,116,101,115,32,33]);

var g_cst21_G_exo04 = new G_ScmString([115,97,110,115,32,97,118,111,105,114,32,98,101,115,111,105,110]);

var g_cst22_G_exo04 = new G_ScmString([113,117,39,111,110,32,118,101,117,116,32]);

function g_bb1_exo04_23_() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_exo04_23_);
  }
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_exo04_23_);
  } else {
    g_nargs = 0;
    return g_bb1_main();
  }
}

g_bb1_exo04_23_.id = 0;
g_bb1_exo04_23_.parent = g_bb1_exo04_23_;
g_bb1_exo04_23_.nfree = -1;
g_bb1_exo04_23_._name = g_make_interned_symbol("exo04#");
g_bb1_exo04_23_.ctrlpts = null;
g_bb1_exo04_23_.info = false;

function g_bb2_exo04_23_() {
  g_nargs = 0;
  return g_bb1_main();
}

g_bb2_exo04_23_.id = 1;
g_bb2_exo04_23_.parent = g_bb1_exo04_23_;


g_bb1_exo04_23_.ctrlpts = [g_bb1_exo04_23_,g_bb2_exo04_23_];


g_peps["exo04#"] = g_bb1_exo04_23_;
g_glo["exo04#"] = g_bb1_exo04_23_;

function g_bb1_car() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_car);
  }
  if (g_r1 instanceof G_Pair) {
    g_r1 = g_r1.car;
    return g_r0;
  } else {
    g_r1 = g_cst0_G_exo04;
    if (--g_pollcount === 0) {
      return g_poll(g_bb3_car);
    } else {
      g_nargs = 1;
      return g_bb1_error();
    }
  }
}

g_bb1_car.id = 0;
g_bb1_car.parent = g_bb1_car;
g_bb1_car.nfree = -1;
g_bb1_car._name = g_make_interned_symbol("car");
g_bb1_car.ctrlpts = null;
g_bb1_car.info = false;

function g_bb4_car() {
  g_r1 = g_r1.car;
  return g_r0;
}

g_bb4_car.id = 1;
g_bb4_car.parent = g_bb1_car;

function g_bb2_car() {
  g_r1 = g_cst0_G_exo04;
  if (--g_pollcount === 0) {
    return g_poll(g_bb3_car);
  } else {
    g_nargs = 1;
    return g_bb1_error();
  }
}

g_bb2_car.id = 2;
g_bb2_car.parent = g_bb1_car;

function g_bb3_car() {
  g_nargs = 1;
  return g_bb1_error();
}

g_bb3_car.id = 3;
g_bb3_car.parent = g_bb1_car;


g_bb1_car.ctrlpts = [g_bb1_car,g_bb4_car,g_bb2_car,g_bb3_car];


g_peps["car"] = g_bb1_car;
g_glo["car"] = g_bb1_car;

function g_bb1_cdr() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_cdr);
  }
  if (g_r1 instanceof G_Pair) {
    g_r1 = g_r1.cdr;
    return g_r0;
  } else {
    g_r1 = g_cst1_G_exo04;
    if (--g_pollcount === 0) {
      return g_poll(g_bb3_cdr);
    } else {
      g_nargs = 1;
      return g_bb1_error();
    }
  }
}

g_bb1_cdr.id = 0;
g_bb1_cdr.parent = g_bb1_cdr;
g_bb1_cdr.nfree = -1;
g_bb1_cdr._name = g_make_interned_symbol("cdr");
g_bb1_cdr.ctrlpts = null;
g_bb1_cdr.info = false;

function g_bb4_cdr() {
  g_r1 = g_r1.cdr;
  return g_r0;
}

g_bb4_cdr.id = 1;
g_bb4_cdr.parent = g_bb1_cdr;

function g_bb2_cdr() {
  g_r1 = g_cst1_G_exo04;
  if (--g_pollcount === 0) {
    return g_poll(g_bb3_cdr);
  } else {
    g_nargs = 1;
    return g_bb1_error();
  }
}

g_bb2_cdr.id = 2;
g_bb2_cdr.parent = g_bb1_cdr;

function g_bb3_cdr() {
  g_nargs = 1;
  return g_bb1_error();
}

g_bb3_cdr.id = 3;
g_bb3_cdr.parent = g_bb1_cdr;


g_bb1_cdr.ctrlpts = [g_bb1_cdr,g_bb4_cdr,g_bb2_cdr,g_bb3_cdr];


g_peps["cdr"] = g_bb1_cdr;
g_glo["cdr"] = g_bb1_cdr;

function g_bb1_error() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_error);
  }
  var msg = '*** ERROR -- ' + g_scm2host(g_r1);
      if (this.hasOwnProperty('console')) console.log(msg); else alert(msg);
      process.exit(1);g_r1 = void 0;
  return g_r0;
}

g_bb1_error.id = 0;
g_bb1_error.parent = g_bb1_error;
g_bb1_error.nfree = -1;
g_bb1_error._name = g_make_interned_symbol("error");
g_bb1_error.ctrlpts = null;
g_bb1_error.info = false;


g_bb1_error.ctrlpts = [g_bb1_error];


g_peps["error"] = g_bb1_error;
g_glo["error"] = g_bb1_error;

function g_bb1_log() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_log);
  }
  console.log(g_scm2host(g_r1));g_r1 = void 0;
  return g_r0;
}

g_bb1_log.id = 0;
g_bb1_log.parent = g_bb1_log;
g_bb1_log.nfree = -1;
g_bb1_log._name = g_make_interned_symbol("log");
g_bb1_log.ctrlpts = null;
g_bb1_log.info = false;


g_bb1_log.ctrlpts = [g_bb1_log];


g_peps["log"] = g_bb1_log;
g_glo["log"] = g_bb1_log;

function g_bb1_string_2d_append_2d_2() { // entry-point
  if (g_nargs !== 2) {
    return g_wrong_nargs(g_bb1_string_2d_append_2d_2);
  }
  g_r1 = g_host2scm(g_scm2host(g_r1)+g_scm2host(g_r2));
  return g_r0;
}

g_bb1_string_2d_append_2d_2.id = 0;
g_bb1_string_2d_append_2d_2.parent = g_bb1_string_2d_append_2d_2;
g_bb1_string_2d_append_2d_2.nfree = -1;
g_bb1_string_2d_append_2d_2._name = g_make_interned_symbol("string-append-2");
g_bb1_string_2d_append_2d_2.ctrlpts = null;
g_bb1_string_2d_append_2d_2.info = false;


g_bb1_string_2d_append_2d_2.ctrlpts = [g_bb1_string_2d_append_2d_2];


g_peps["string-append-2"] = g_bb1_string_2d_append_2d_2;
g_glo["string-append-2"] = g_bb1_string_2d_append_2d_2;

function g_bb1_string_2d_append_2d_list() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_string_2d_append_2d_list);
  }
  if (g_r1 === null) {
    return g_bb14_string_2d_append_2d_list();
  } else {
    if (g_r1 instanceof G_Pair) {
      return g_bb2_string_2d_append_2d_list();
    } else {
      return g_bb6_string_2d_append_2d_list();
    }
  }
}

g_bb1_string_2d_append_2d_list.id = 0;
g_bb1_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;
g_bb1_string_2d_append_2d_list.nfree = -1;
g_bb1_string_2d_append_2d_list._name = g_make_interned_symbol("string-append-list");
g_bb1_string_2d_append_2d_list.ctrlpts = null;
g_bb1_string_2d_append_2d_list.info = false;

function g_bb14_string_2d_append_2d_list() {
  g_r1 = g_cst2_G_exo04;
  return g_r0;
}

g_bb14_string_2d_append_2d_list.id = 1;
g_bb14_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;

function g_bb5_string_2d_append_2d_list() {
  if (g_r1 instanceof G_Pair) {
    g_r2 = g_r1.car;
    g_stack[g_sp+1] = g_r2;
    g_stack[g_sp+2] = g_r0;
    if (g_r1 instanceof G_Pair) {
      g_sp += 2;
      g_r1 = g_r1.cdr;
      g_r0 = g_bb12_string_2d_append_2d_list;
      if (--g_pollcount === 0) {
        return g_poll(g_bb4_string_2d_append_2d_list);
      } else {
        if (g_r1 === null) {
          return g_bb14_string_2d_append_2d_list();
        } else {
          if (g_r1 instanceof G_Pair) {
            return g_bb2_string_2d_append_2d_list();
          } else {
            return g_bb6_string_2d_append_2d_list();
          }
        }
      }
    } else {
      g_sp += 2;
      g_r0 = g_bb10_string_2d_append_2d_list;
      g_nargs = 1;
      return g_peps["cdr"]();
    }
  } else {
    g_stack[g_sp+1] = g_r0;
    g_stack[g_sp+2] = g_r1;
    g_r0 = g_bb7_string_2d_append_2d_list;
    g_nargs = 1;
    g_sp += 2;
    return g_peps["car"]();
  }
}

g_bb5_string_2d_append_2d_list.id = 2;
g_bb5_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;

function g_bb2_string_2d_append_2d_list() {
  g_r2 = g_r1.car;
  g_stack[g_sp+1] = g_r2;
  g_stack[g_sp+2] = g_r0;
  if (g_r1 instanceof G_Pair) {
    g_sp += 2;
    g_r1 = g_r1.cdr;
    g_r0 = g_bb12_string_2d_append_2d_list;
    if (--g_pollcount === 0) {
      return g_poll(g_bb4_string_2d_append_2d_list);
    } else {
      if (g_r1 === null) {
        return g_bb14_string_2d_append_2d_list();
      } else {
        if (g_r1 instanceof G_Pair) {
          return g_bb2_string_2d_append_2d_list();
        } else {
          return g_bb6_string_2d_append_2d_list();
        }
      }
    }
  } else {
    g_sp += 2;
    g_r0 = g_bb10_string_2d_append_2d_list;
    g_nargs = 1;
    return g_peps["cdr"]();
  }
}

g_bb2_string_2d_append_2d_list.id = 3;
g_bb2_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;

function g_bb6_string_2d_append_2d_list() {
  g_stack[g_sp+1] = g_r0;
  g_stack[g_sp+2] = g_r1;
  g_r0 = g_bb7_string_2d_append_2d_list;
  g_nargs = 1;
  g_sp += 2;
  return g_peps["car"]();
}

g_bb6_string_2d_append_2d_list.id = 4;
g_bb6_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;

function g_bb3_string_2d_append_2d_list() {
  g_r1 = g_r1.cdr;
  g_r0 = g_bb12_string_2d_append_2d_list;
  if (--g_pollcount === 0) {
    return g_poll(g_bb4_string_2d_append_2d_list);
  } else {
    if (g_r1 === null) {
      return g_bb14_string_2d_append_2d_list();
    } else {
      if (g_r1 instanceof G_Pair) {
        return g_bb2_string_2d_append_2d_list();
      } else {
        return g_bb6_string_2d_append_2d_list();
      }
    }
  }
}

g_bb3_string_2d_append_2d_list.id = 5;
g_bb3_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;

function g_bb4_string_2d_append_2d_list() {
  if (g_r1 === null) {
    return g_bb14_string_2d_append_2d_list();
  } else {
    if (g_r1 instanceof G_Pair) {
      return g_bb2_string_2d_append_2d_list();
    } else {
      return g_bb6_string_2d_append_2d_list();
    }
  }
}

g_bb4_string_2d_append_2d_list.id = 6;
g_bb4_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;

function g_bb12_string_2d_append_2d_list() { // return-point
  g_r2 = g_r1;
  g_r0 = g_stack[g_sp];
  g_r1 = g_stack[g_sp-1];
  if (--g_pollcount === 0) {
    return g_poll(g_bb13_string_2d_append_2d_list);
  } else {
    g_nargs = 2;
    g_sp -= 2;
    return g_bb1_string_2d_append_2d_2();
  }
}

g_bb12_string_2d_append_2d_list.id = 7;
g_bb12_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;
g_bb12_string_2d_append_2d_list.fs = 2;
g_bb12_string_2d_append_2d_list.link = 2;

function g_bb9_string_2d_append_2d_list() {
  g_r0 = g_bb10_string_2d_append_2d_list;
  g_nargs = 1;
  return g_peps["cdr"]();
}

g_bb9_string_2d_append_2d_list.id = 8;
g_bb9_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;

function g_bb10_string_2d_append_2d_list() { // return-point
  return g_bb11_string_2d_append_2d_list();
}

g_bb10_string_2d_append_2d_list.id = 9;
g_bb10_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;
g_bb10_string_2d_append_2d_list.fs = 2;
g_bb10_string_2d_append_2d_list.link = 2;

function g_bb7_string_2d_append_2d_list() { // return-point
  return g_bb8_string_2d_append_2d_list();
}

g_bb7_string_2d_append_2d_list.id = 10;
g_bb7_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;
g_bb7_string_2d_append_2d_list.fs = 2;
g_bb7_string_2d_append_2d_list.link = 1;

function g_bb13_string_2d_append_2d_list() {
  g_nargs = 2;
  g_sp -= 2;
  return g_bb1_string_2d_append_2d_2();
}

g_bb13_string_2d_append_2d_list.id = 11;
g_bb13_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;

function g_bb11_string_2d_append_2d_list() {
  return g_bb11_string_2d_append_2d_list();
}

g_bb11_string_2d_append_2d_list.id = 12;
g_bb11_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;

function g_bb8_string_2d_append_2d_list() {
  return g_bb8_string_2d_append_2d_list();
}

g_bb8_string_2d_append_2d_list.id = 13;
g_bb8_string_2d_append_2d_list.parent = g_bb1_string_2d_append_2d_list;


g_bb1_string_2d_append_2d_list.ctrlpts = [g_bb1_string_2d_append_2d_list,g_bb14_string_2d_append_2d_list,g_bb5_string_2d_append_2d_list,g_bb2_string_2d_append_2d_list,g_bb6_string_2d_append_2d_list,g_bb3_string_2d_append_2d_list,g_bb4_string_2d_append_2d_list,g_bb12_string_2d_append_2d_list,g_bb9_string_2d_append_2d_list,g_bb10_string_2d_append_2d_list,g_bb7_string_2d_append_2d_list,g_bb13_string_2d_append_2d_list,g_bb11_string_2d_append_2d_list,g_bb8_string_2d_append_2d_list];


g_peps["string-append-list"] = g_bb1_string_2d_append_2d_list;
g_glo["string-append-list"] = g_bb1_string_2d_append_2d_list;

function g_bb1_string_2d_append_2d_multiarg() { // entry-point (+rest)
  if (g_nargs === 0) {
    g_r1 = null;
  } else {
    if (!g_build_rest(0)) {
      return g_wrong_nargs(g_bb1_string_2d_append_2d_multiarg);
    }
  }
  if (g_r1 === null) {
    g_r1 = g_cst3_G_exo04;
    return g_r0;
  } else {
    if (g_r1 instanceof G_Pair) {
      g_r2 = g_r1.car;
      g_stack[g_sp+1] = g_r2;
      g_stack[g_sp+2] = g_r0;
      if (g_r1 instanceof G_Pair) {
        g_sp += 2;
        g_r1 = g_r1.cdr;
        if (--g_pollcount === 0) {
          return g_poll(g_bb5_string_2d_append_2d_multiarg);
        } else {
          g_r0 = g_bb6_string_2d_append_2d_multiarg;
          g_nargs = 1;
          return g_bb1_string_2d_append_2d_multiarg();
        }
      } else {
        g_sp += 2;
        g_r0 = g_bb9_string_2d_append_2d_multiarg;
        g_nargs = 1;
        return g_peps["cdr"]();
      }
    } else {
      g_stack[g_sp+1] = g_r0;
      g_stack[g_sp+2] = g_r1;
      g_r0 = g_bb12_string_2d_append_2d_multiarg;
      g_nargs = 1;
      g_sp += 2;
      return g_peps["car"]();
    }
  }
}

g_bb1_string_2d_append_2d_multiarg.id = 0;
g_bb1_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;
g_bb1_string_2d_append_2d_multiarg.nfree = -1;
g_bb1_string_2d_append_2d_multiarg._name = g_make_interned_symbol("string-append-multiarg");
g_bb1_string_2d_append_2d_multiarg.ctrlpts = null;
g_bb1_string_2d_append_2d_multiarg.info = false;

function g_bb14_string_2d_append_2d_multiarg() {
  g_r1 = g_cst3_G_exo04;
  return g_r0;
}

g_bb14_string_2d_append_2d_multiarg.id = 1;
g_bb14_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;

function g_bb2_string_2d_append_2d_multiarg() {
  if (g_r1 instanceof G_Pair) {
    g_r2 = g_r1.car;
    g_stack[g_sp+1] = g_r2;
    g_stack[g_sp+2] = g_r0;
    if (g_r1 instanceof G_Pair) {
      g_sp += 2;
      g_r1 = g_r1.cdr;
      if (--g_pollcount === 0) {
        return g_poll(g_bb5_string_2d_append_2d_multiarg);
      } else {
        g_r0 = g_bb6_string_2d_append_2d_multiarg;
        g_nargs = 1;
        return g_bb1_string_2d_append_2d_multiarg();
      }
    } else {
      g_sp += 2;
      g_r0 = g_bb9_string_2d_append_2d_multiarg;
      g_nargs = 1;
      return g_peps["cdr"]();
    }
  } else {
    g_stack[g_sp+1] = g_r0;
    g_stack[g_sp+2] = g_r1;
    g_r0 = g_bb12_string_2d_append_2d_multiarg;
    g_nargs = 1;
    g_sp += 2;
    return g_peps["car"]();
  }
}

g_bb2_string_2d_append_2d_multiarg.id = 2;
g_bb2_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;

function g_bb3_string_2d_append_2d_multiarg() {
  g_r2 = g_r1.car;
  g_stack[g_sp+1] = g_r2;
  g_stack[g_sp+2] = g_r0;
  if (g_r1 instanceof G_Pair) {
    g_sp += 2;
    g_r1 = g_r1.cdr;
    if (--g_pollcount === 0) {
      return g_poll(g_bb5_string_2d_append_2d_multiarg);
    } else {
      g_r0 = g_bb6_string_2d_append_2d_multiarg;
      g_nargs = 1;
      return g_bb1_string_2d_append_2d_multiarg();
    }
  } else {
    g_sp += 2;
    g_r0 = g_bb9_string_2d_append_2d_multiarg;
    g_nargs = 1;
    return g_peps["cdr"]();
  }
}

g_bb3_string_2d_append_2d_multiarg.id = 3;
g_bb3_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;

function g_bb4_string_2d_append_2d_multiarg() {
  g_r1 = g_r1.cdr;
  if (--g_pollcount === 0) {
    return g_poll(g_bb5_string_2d_append_2d_multiarg);
  } else {
    g_r0 = g_bb6_string_2d_append_2d_multiarg;
    g_nargs = 1;
    return g_bb1_string_2d_append_2d_multiarg();
  }
}

g_bb4_string_2d_append_2d_multiarg.id = 4;
g_bb4_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;

function g_bb5_string_2d_append_2d_multiarg() {
  g_r0 = g_bb6_string_2d_append_2d_multiarg;
  g_nargs = 1;
  return g_bb1_string_2d_append_2d_multiarg();
}

g_bb5_string_2d_append_2d_multiarg.id = 5;
g_bb5_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;

function g_bb6_string_2d_append_2d_multiarg() { // return-point
  g_r2 = g_r1;
  g_r0 = g_stack[g_sp];
  g_r1 = g_stack[g_sp-1];
  if (--g_pollcount === 0) {
    return g_poll(g_bb7_string_2d_append_2d_multiarg);
  } else {
    g_nargs = 2;
    g_sp -= 2;
    return g_bb1_string_2d_append_2d_2();
  }
}

g_bb6_string_2d_append_2d_multiarg.id = 6;
g_bb6_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;
g_bb6_string_2d_append_2d_multiarg.fs = 2;
g_bb6_string_2d_append_2d_multiarg.link = 2;

function g_bb8_string_2d_append_2d_multiarg() {
  g_r0 = g_bb9_string_2d_append_2d_multiarg;
  g_nargs = 1;
  return g_peps["cdr"]();
}

g_bb8_string_2d_append_2d_multiarg.id = 7;
g_bb8_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;

function g_bb9_string_2d_append_2d_multiarg() { // return-point
  return g_bb10_string_2d_append_2d_multiarg();
}

g_bb9_string_2d_append_2d_multiarg.id = 8;
g_bb9_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;
g_bb9_string_2d_append_2d_multiarg.fs = 2;
g_bb9_string_2d_append_2d_multiarg.link = 2;

function g_bb11_string_2d_append_2d_multiarg() {
  g_stack[g_sp+1] = g_r0;
  g_stack[g_sp+2] = g_r1;
  g_r0 = g_bb12_string_2d_append_2d_multiarg;
  g_nargs = 1;
  g_sp += 2;
  return g_peps["car"]();
}

g_bb11_string_2d_append_2d_multiarg.id = 9;
g_bb11_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;

function g_bb12_string_2d_append_2d_multiarg() { // return-point
  return g_bb13_string_2d_append_2d_multiarg();
}

g_bb12_string_2d_append_2d_multiarg.id = 10;
g_bb12_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;
g_bb12_string_2d_append_2d_multiarg.fs = 2;
g_bb12_string_2d_append_2d_multiarg.link = 1;

function g_bb7_string_2d_append_2d_multiarg() {
  g_nargs = 2;
  g_sp -= 2;
  return g_bb1_string_2d_append_2d_2();
}

g_bb7_string_2d_append_2d_multiarg.id = 11;
g_bb7_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;

function g_bb10_string_2d_append_2d_multiarg() {
  return g_bb10_string_2d_append_2d_multiarg();
}

g_bb10_string_2d_append_2d_multiarg.id = 12;
g_bb10_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;

function g_bb13_string_2d_append_2d_multiarg() {
  return g_bb13_string_2d_append_2d_multiarg();
}

g_bb13_string_2d_append_2d_multiarg.id = 13;
g_bb13_string_2d_append_2d_multiarg.parent = g_bb1_string_2d_append_2d_multiarg;


g_bb1_string_2d_append_2d_multiarg.ctrlpts = [g_bb1_string_2d_append_2d_multiarg,g_bb14_string_2d_append_2d_multiarg,g_bb2_string_2d_append_2d_multiarg,g_bb3_string_2d_append_2d_multiarg,g_bb4_string_2d_append_2d_multiarg,g_bb5_string_2d_append_2d_multiarg,g_bb6_string_2d_append_2d_multiarg,g_bb8_string_2d_append_2d_multiarg,g_bb9_string_2d_append_2d_multiarg,g_bb11_string_2d_append_2d_multiarg,g_bb12_string_2d_append_2d_multiarg,g_bb7_string_2d_append_2d_multiarg,g_bb10_string_2d_append_2d_multiarg,g_bb13_string_2d_append_2d_multiarg];


g_peps["string-append-multiarg"] = g_bb1_string_2d_append_2d_multiarg;
g_glo["string-append-multiarg"] = g_bb1_string_2d_append_2d_multiarg;

function g_bb1_main() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_main);
  }
  g_stack[g_sp+1] = g_r0;
  g_r2 = g_cst4_G_exo04;
  g_r1 = g_cst5_G_exo04;
  ++g_sp;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_main);
  } else {
    g_r0 = g_bb3_main;
    g_nargs = 2;
    return g_bb1_string_2d_append_2d_2();
  }
}

g_bb1_main.id = 0;
g_bb1_main.parent = g_bb1_main;
g_bb1_main.nfree = -1;
g_bb1_main._name = g_make_interned_symbol("main");
g_bb1_main.ctrlpts = null;
g_bb1_main.info = false;

function g_bb2_main() {
  g_r0 = g_bb3_main;
  g_nargs = 2;
  return g_bb1_string_2d_append_2d_2();
}

g_bb2_main.id = 1;
g_bb2_main.parent = g_bb1_main;

function g_bb3_main() { // return-point
  g_r0 = g_bb4_main;
  g_nargs = 1;
  return g_peps["log"]();
}

g_bb3_main.id = 2;
g_bb3_main.parent = g_bb1_main;
g_bb3_main.fs = 1;
g_bb3_main.link = 1;

function g_bb4_main() { // return-point
  g_r1 = g_cst6_G_exo04;
  g_r0 = g_bb5_main;
  g_nargs = 1;
  return g_bb1_string_2d_append_2d_list();
}

g_bb4_main.id = 3;
g_bb4_main.parent = g_bb1_main;
g_bb4_main.fs = 1;
g_bb4_main.link = 1;

function g_bb5_main() { // return-point
  g_r0 = g_bb6_main;
  g_nargs = 1;
  return g_peps["log"]();
}

g_bb5_main.id = 4;
g_bb5_main.parent = g_bb1_main;
g_bb5_main.fs = 1;
g_bb5_main.link = 1;

function g_bb6_main() { // return-point
  g_stack[g_sp+1] = g_cst16_G_exo04;
  g_stack[g_sp+2] = g_cst17_G_exo04;
  g_stack[g_sp+3] = g_cst18_G_exo04;
  g_stack[g_sp+4] = g_cst19_G_exo04;
  g_r3 = g_cst20_G_exo04;
  g_r2 = g_cst21_G_exo04;
  g_r1 = g_cst22_G_exo04;
  g_r0 = g_bb7_main;
  g_nargs = 7;
  g_sp += 4;
  return g_bb1_string_2d_append_2d_multiarg();
}

g_bb6_main.id = 5;
g_bb6_main.parent = g_bb1_main;
g_bb6_main.fs = 1;
g_bb6_main.link = 1;

function g_bb7_main() { // return-point
  g_r0 = g_stack[g_sp];
  if (--g_pollcount === 0) {
    return g_poll(g_bb8_main);
  } else {
    g_nargs = 1;
    --g_sp;
    return g_peps["log"]();
  }
}

g_bb7_main.id = 6;
g_bb7_main.parent = g_bb1_main;
g_bb7_main.fs = 1;
g_bb7_main.link = 1;

function g_bb8_main() {
  g_nargs = 1;
  --g_sp;
  return g_peps["log"]();
}

g_bb8_main.id = 7;
g_bb8_main.parent = g_bb1_main;


g_bb1_main.ctrlpts = [g_bb1_main,g_bb2_main,g_bb3_main,g_bb4_main,g_bb5_main,g_bb6_main,g_bb7_main,g_bb8_main];


g_peps["main"] = g_bb1_main;
g_glo["main"] = g_bb1_main;

g_module_register([[g_make_interned_symbol("exo04")],[],null,1,g_bb1_exo04_23_,false]);

