// File generated by Gambit v4.9.3
// Link info: (409003 (js ()) "exo03" (("exo03")) (module_register glo peps make_interned_symbol sp stack string r0 r1 ffi poll pollcount wrong_nargs nargs) () (body-append-br colored-div button-click-set! main exo03# btn-color body-append) () #f)

var g_cst0_G_exo03 = new G_ScmString([60,98,114,47,62]);

var g_cst1_G_exo03 = new G_ScmString([60,100,105,118,32,105,100,61,34,99,111,108,34,62,60,47,100,105,118,62]);

var g_cst2_G_exo03 = new G_ScmString([121,101,108,108,111,119]);

var g_cst3_G_exo03 = new G_ScmString([98,108,117,101]);

var g_cst4_G_exo03 = new G_ScmString([114,101,100]);

var g_cst5_G_exo03 = new G_ScmString([121,101,108,108,111,119]);

var g_cst6_G_exo03 = new G_ScmString([35,50,56,70,49,53,67]);

var g_cst7_G_exo03 = new G_ScmString([114,103,98,40,50,51,48,44,49,49,50,44,52,53,41]);

function g_bb1_exo03_23_() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_exo03_23_);
  }
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_exo03_23_);
  } else {
    g_nargs = 0;
    return g_bb1_main();
  }
}

g_bb1_exo03_23_.id = 0;
g_bb1_exo03_23_.parent = g_bb1_exo03_23_;
g_bb1_exo03_23_.nfree = -1;
g_bb1_exo03_23_._name = g_make_interned_symbol("exo03#");
g_bb1_exo03_23_.ctrlpts = null;
g_bb1_exo03_23_.info = false;

function g_bb2_exo03_23_() {
  g_nargs = 0;
  return g_bb1_main();
}

g_bb2_exo03_23_.id = 1;
g_bb2_exo03_23_.parent = g_bb1_exo03_23_;


g_bb1_exo03_23_.ctrlpts = [g_bb1_exo03_23_,g_bb2_exo03_23_];


g_peps["exo03#"] = g_bb1_exo03_23_;
g_glo["exo03#"] = g_bb1_exo03_23_;

function g_bb1_body_2d_append() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_body_2d_append);
  }
  body.innerHTML += (g_scm2host(g_r1));g_r1 = void 0;
  return g_r0;
}

g_bb1_body_2d_append.id = 0;
g_bb1_body_2d_append.parent = g_bb1_body_2d_append;
g_bb1_body_2d_append.nfree = -1;
g_bb1_body_2d_append._name = g_make_interned_symbol("body-append");
g_bb1_body_2d_append.ctrlpts = null;
g_bb1_body_2d_append.info = false;


g_bb1_body_2d_append.ctrlpts = [g_bb1_body_2d_append];


g_peps["body-append"] = g_bb1_body_2d_append;
g_glo["body-append"] = g_bb1_body_2d_append;

function g_bb1_body_2d_append_2d_br() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_body_2d_append_2d_br);
  }
  body.innerHTML += (g_scm2host(g_r1));g_r1 = g_cst0_G_exo03;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_body_2d_append_2d_br);
  } else {
    g_nargs = 1;
    return g_bb1_body_2d_append();
  }
}

g_bb1_body_2d_append_2d_br.id = 0;
g_bb1_body_2d_append_2d_br.parent = g_bb1_body_2d_append_2d_br;
g_bb1_body_2d_append_2d_br.nfree = -1;
g_bb1_body_2d_append_2d_br._name = g_make_interned_symbol("body-append-br");
g_bb1_body_2d_append_2d_br.ctrlpts = null;
g_bb1_body_2d_append_2d_br.info = false;

function g_bb2_body_2d_append_2d_br() {
  g_nargs = 1;
  return g_bb1_body_2d_append();
}

g_bb2_body_2d_append_2d_br.id = 1;
g_bb2_body_2d_append_2d_br.parent = g_bb1_body_2d_append_2d_br;


g_bb1_body_2d_append_2d_br.ctrlpts = [g_bb1_body_2d_append_2d_br,g_bb2_body_2d_append_2d_br];


g_peps["body-append-br"] = g_bb1_body_2d_append_2d_br;
g_glo["body-append-br"] = g_bb1_body_2d_append_2d_br;

function g_bb1_btn_2d_color() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_btn_2d_color);
  }
  g_r1 = g_host2scm("<button onclick=\"colorise('"+g_scm2host(g_r1)+"')\">"+g_scm2host(g_r1)+"</button>");
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_btn_2d_color);
  } else {
    g_nargs = 1;
    return g_bb1_body_2d_append_2d_br();
  }
}

g_bb1_btn_2d_color.id = 0;
g_bb1_btn_2d_color.parent = g_bb1_btn_2d_color;
g_bb1_btn_2d_color.nfree = -1;
g_bb1_btn_2d_color._name = g_make_interned_symbol("btn-color");
g_bb1_btn_2d_color.ctrlpts = null;
g_bb1_btn_2d_color.info = false;

function g_bb2_btn_2d_color() {
  g_nargs = 1;
  return g_bb1_body_2d_append_2d_br();
}

g_bb2_btn_2d_color.id = 1;
g_bb2_btn_2d_color.parent = g_bb1_btn_2d_color;


g_bb1_btn_2d_color.ctrlpts = [g_bb1_btn_2d_color,g_bb2_btn_2d_color];


g_peps["btn-color"] = g_bb1_btn_2d_color;
g_glo["btn-color"] = g_bb1_btn_2d_color;

function g_bb1_colored_2d_div() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_colored_2d_div);
  }
  g_r1 = g_cst1_G_exo03;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_colored_2d_div);
  } else {
    g_nargs = 1;
    return g_bb1_body_2d_append();
  }
}

g_bb1_colored_2d_div.id = 0;
g_bb1_colored_2d_div.parent = g_bb1_colored_2d_div;
g_bb1_colored_2d_div.nfree = -1;
g_bb1_colored_2d_div._name = g_make_interned_symbol("colored-div");
g_bb1_colored_2d_div.ctrlpts = null;
g_bb1_colored_2d_div.info = false;

function g_bb2_colored_2d_div() {
  g_nargs = 1;
  return g_bb1_body_2d_append();
}

g_bb2_colored_2d_div.id = 1;
g_bb2_colored_2d_div.parent = g_bb1_colored_2d_div;


g_bb1_colored_2d_div.ctrlpts = [g_bb1_colored_2d_div,g_bb2_colored_2d_div];


g_peps["colored-div"] = g_bb1_colored_2d_div;
g_glo["colored-div"] = g_bb1_colored_2d_div;

function g_bb1_button_2d_click_2d_set_21_() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb1_button_2d_click_2d_set_21_);
  }
  colorise = g_scm2host(g_r1);g_r1 = void 0;
  return g_r0;
}

g_bb1_button_2d_click_2d_set_21_.id = 0;
g_bb1_button_2d_click_2d_set_21_.parent = g_bb1_button_2d_click_2d_set_21_;
g_bb1_button_2d_click_2d_set_21_.nfree = -1;
g_bb1_button_2d_click_2d_set_21_._name = g_make_interned_symbol("button-click-set!");
g_bb1_button_2d_click_2d_set_21_.ctrlpts = null;
g_bb1_button_2d_click_2d_set_21_.info = false;


g_bb1_button_2d_click_2d_set_21_.ctrlpts = [g_bb1_button_2d_click_2d_set_21_];


g_peps["button-click-set!"] = g_bb1_button_2d_click_2d_set_21_;
g_glo["button-click-set!"] = g_bb1_button_2d_click_2d_set_21_;

function g_bb1_main() { // entry-point
  if (g_nargs !== 0) {
    return g_wrong_nargs(g_bb1_main);
  }
  g_stack[g_sp+1] = g_r0;
  g_r1 = g_cst2_G_exo03;
  ++g_sp;
  if (--g_pollcount === 0) {
    return g_poll(g_bb2_main);
  } else {
    g_r0 = g_bb3_main;
    g_nargs = 1;
    return g_bb1_btn_2d_color();
  }
}

g_bb1_main.id = 0;
g_bb1_main.parent = g_bb1_main;
g_bb1_main.nfree = -1;
g_bb1_main._name = g_make_interned_symbol("main");
g_bb1_main.ctrlpts = null;
g_bb1_main.info = false;

function g_bb2_main() {
  g_r0 = g_bb3_main;
  g_nargs = 1;
  return g_bb1_btn_2d_color();
}

g_bb2_main.id = 1;
g_bb2_main.parent = g_bb1_main;

function g_bb3_main() { // return-point
  g_r1 = g_cst3_G_exo03;
  g_r0 = g_bb4_main;
  g_nargs = 1;
  return g_bb1_btn_2d_color();
}

g_bb3_main.id = 2;
g_bb3_main.parent = g_bb1_main;
g_bb3_main.fs = 1;
g_bb3_main.link = 1;

function g_bb4_main() { // return-point
  g_r1 = g_cst4_G_exo03;
  g_r0 = g_bb5_main;
  g_nargs = 1;
  return g_bb1_btn_2d_color();
}

g_bb4_main.id = 3;
g_bb4_main.parent = g_bb1_main;
g_bb4_main.fs = 1;
g_bb4_main.link = 1;

function g_bb5_main() { // return-point
  g_r1 = g_cst5_G_exo03;
  g_r0 = g_bb6_main;
  g_nargs = 1;
  return g_bb1_btn_2d_color();
}

g_bb5_main.id = 4;
g_bb5_main.parent = g_bb1_main;
g_bb5_main.fs = 1;
g_bb5_main.link = 1;

function g_bb6_main() { // return-point
  g_r1 = g_cst6_G_exo03;
  g_r0 = g_bb7_main;
  g_nargs = 1;
  return g_bb1_btn_2d_color();
}

g_bb6_main.id = 5;
g_bb6_main.parent = g_bb1_main;
g_bb6_main.fs = 1;
g_bb6_main.link = 1;

function g_bb7_main() { // return-point
  g_r1 = g_cst7_G_exo03;
  g_r0 = g_bb8_main;
  g_nargs = 1;
  return g_bb1_btn_2d_color();
}

g_bb7_main.id = 6;
g_bb7_main.parent = g_bb1_main;
g_bb7_main.fs = 1;
g_bb7_main.link = 1;

function g_bb8_main() { // return-point
  g_r0 = g_bb9_main;
  g_nargs = 0;
  return g_bb1_colored_2d_div();
}

g_bb8_main.id = 7;
g_bb8_main.parent = g_bb1_main;
g_bb8_main.fs = 1;
g_bb8_main.link = 1;

function g_bb9_main() { // return-point
  g_r1 = g_bb11_main;
  g_r0 = g_stack[g_sp];
  if (--g_pollcount === 0) {
    return g_poll(g_bb10_main);
  } else {
    g_nargs = 1;
    --g_sp;
    return g_bb1_button_2d_click_2d_set_21_();
  }
}

g_bb9_main.id = 8;
g_bb9_main.parent = g_bb1_main;
g_bb9_main.fs = 1;
g_bb9_main.link = 1;

function g_bb11_main() { // entry-point
  if (g_nargs !== 1) {
    return g_wrong_nargs(g_bb11_main);
  }
  document.getElementById('col').style.backgroundColor = g_scm2host(g_r1) ;g_r1 = void 0;
  return g_r0;
}

g_bb11_main.id = 9;
g_bb11_main.parent = g_bb1_main;
g_bb11_main.nfree = -1;

function g_bb10_main() {
  g_nargs = 1;
  --g_sp;
  return g_bb1_button_2d_click_2d_set_21_();
}

g_bb10_main.id = 10;
g_bb10_main.parent = g_bb1_main;


g_bb1_main.ctrlpts = [g_bb1_main,g_bb2_main,g_bb3_main,g_bb4_main,g_bb5_main,g_bb6_main,g_bb7_main,g_bb8_main,g_bb9_main,g_bb11_main,g_bb10_main];


g_peps["main"] = g_bb1_main;
g_glo["main"] = g_bb1_main;

g_module_register([[g_make_interned_symbol("exo03")],[],null,1,g_bb1_exo03_23_,false]);

